# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictBool,
    StrictInt,
    StrictStr,
)


class Model(RootModel[Any]):
    root: Any


class EventEnvelope(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: StrictStr = Field(..., max_length=200, min_length=1)
    seq: StrictInt = Field(..., ge=0, le=9007199254740991)
    ts: StrictStr = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$',
    )
    data: Any | None = None


class KitError(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    code: StrictStr = Field(..., pattern='^KIT-\\d{4}$')
    message: StrictStr
    retryable: StrictBool
    details: dict[StrictStr, Any] | None = None


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    error: KitError
