import type { SeedCatalog } from "../types.js";

/**
 * Seed catalogue for the NpmGuard benchmark, dataset version 0.1.0.
 *
 * Selection criteria (METHODOLOGY.md §4):
 *   1. Currently published, non-deprecated.
 *   2. ≥10k weekly downloads.
 *   3. Behavioural diversity — pure utilities, network, fs, crypto, build,
 *      native bindings, ESM-vs-CJS dual modes.
 *   4. Loadable in isolation: `node -e "require('<name>')"` succeeds.
 *   5. Source available in the published tarball.
 *
 * The `integrity` field is populated by `npm run lock` from the
 * registry's published `dist.integrity`. Empty strings are placeholders
 * that the fetcher refuses to accept.
 *
 * To add a seed: append the entry with `integrity: ""`, run `npm run lock`,
 * commit the result.
 */
export const SEEDS: SeedCatalog = [
  // ── Tier 1: simple, no I/O on load ────────────────────────────────────
  {
    name: "is-number",
    version: "7.0.0",
    integrity: "sha512-41Cifkg6e8TylSpdtTpeLVMqvSBEVzTttHvERD741+pnZ8ANv0004MRL43QKPDlK9cGvNp6NZWZUBlbGXYxxng==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "tiny", "utility"],
    description: "Returns true if the value is a finite number.",
  },
  {
    name: "ms",
    version: "2.1.3",
    integrity: "sha512-6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "tiny", "time"],
    description: "Tiny millisecond conversion utility.",
  },
  {
    name: "lodash.merge",
    version: "4.6.2",
    integrity: "sha512-0KpjqXRVvrYyCsX1swR/XTK0va6VQkQM6MNo7PqW77ByjAhoARA8EfrP1N4+KlKj8YS0ZUCtRT/YUuhyYDujIQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "utility", "lodash-modular"],
    description: "Deep-merge utility from lodash, individually published.",
  },
  {
    name: "qs",
    version: "6.13.1",
    integrity: "sha512-EJPeIn0CYrGu+hli1xilKAPXODtJ12T0sP63Ijx2/khC2JtuaN3JyNIpvmnkmaEtha9ocbG4A4cMcr+TvqvwQg==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "parser", "query-string"],
    description: "Querystring parsing and stringifying with nested objects.",
  },
  {
    name: "mime-types",
    version: "2.1.35",
    integrity: "sha512-ZDY+bPm5zTTF+YpCrAU9nK0UgICYPT0QtT1NZWFv4s++TNkcgVaT0g6+4R2uI4MjQjzysHB1zxuWL50hzaeXiw==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "lookup", "data-table"],
    description: "MIME-type lookup tables.",
  },
  {
    name: "semver",
    version: "7.6.3",
    integrity: "sha512-oVekP1cKtI+CTDvHWYFUcMtsK/00wmAEfyqKfNdARm8u1wNVhSgaX7A8d4UuIlUI5e84iEwOhs7ZPYRmzU9U6A==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "parser", "version"],
    description: "Semantic version parsing and comparison.",
  },
  {
    name: "cookie",
    version: "1.0.2",
    integrity: "sha512-9Kr/j4O16ISv8zBBhJoi4bXOYNTkFLOqSL3UDB0njXxCXNezjeyVrJyGOWtgfs/q2km1gwBcfH8q1yEGoMYunA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "parser"],
    description: "HTTP cookie parsing/serialization.",
  },
  {
    name: "escape-string-regexp",
    version: "4.0.0",
    integrity: "sha512-TtpcNJ3XAzx3Gq8sWRzJaVajRs0uVxA2YAkdb1jm2YkPz4G6egUFAyA3n5vtEIZefPk5Wa4UXbKuS5fKkJWdgA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "tiny", "regex"],
    description: "Escape RegExp special characters in a string.",
  },
  {
    name: "picocolors",
    version: "1.1.1",
    integrity: "sha512-xceH2snhtb5M9liqDsmEw56le376mTZkEX/jEb/RxNFyegNul7eNslCXP9FDj/Lcu0X8KEyMceP2ntpaHrDEVA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "terminal", "tiny"],
    description: "Smaller, faster alternative to chalk.",
  },
  {
    name: "uuid",
    version: "9.0.1",
    integrity: "sha512-b+1eJOlsR9K8HJpow9Ok3fiWOWSIcIzXodvv0rQjVoOVNpWMpxf1wZNpt4y9h10odCNrqnYp1OBzRktckBe3sA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["crypto-legitimate", "uuid"],
    description: "UUID generation; legitimately uses crypto.",
  },

  // ── Tier 2: utilities with light or legitimate I/O ────────────────────
  {
    name: "dotenv",
    version: "16.4.7",
    integrity: "sha512-47qPchRCykZC03FhkYAhrvwU4xDBFIj1QPqaarj6mdM/hgUzfPHcpkHJOn3mJAufFeeAxAzeGsr5X0M4k6fLZQ==",
    form: "cjs",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "config"],
    description: "Loads environment variables from .env files.",
  },
  {
    name: "debug",
    version: "4.3.7",
    integrity: "sha512-Er2nc/H7RrMXZBFCEim6TCmMk02Z8vLC2Rbi1KEBggpo0fS6l0S1nnapwmIi3yW/+GOJap1Krg4w0Hg80oCqgQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "logging"],
    description: "Tiny JavaScript debugging utility.",
  },
  {
    name: "chalk",
    version: "4.1.2",
    integrity: "sha512-oKnbhFyRIXpUuez8iBMmyEa4nbj4IOQyuhc/wy9kY7/WVPcwIO9VA668Pu8RkO7+0G76SLROeyw9CpQ061i4mA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["terminal", "colors"],
    description: "Terminal string styling done right (last CJS major).",
  },
  {
    name: "commander",
    version: "12.1.0",
    integrity: "sha512-Vw8qHK3bZM9y/P10u3Vib8o/DdkvA2OtPtZvD871QKjy74Wj1WSKFILMPRPSdUSx5RFK1arlJzEtA4PkFgnbuA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "parser"],
    description: "CLI argument parsing framework.",
  },
  {
    name: "glob",
    version: "10.4.5",
    integrity: "sha512-7Bv8RF0k6xjo7d4A/PxYLbUCfb6c+Vpd2/mB2yRDlew7Jb5hEXiCD9ibfO7wpk8i4sevK6DFny9h7EYbM3/sHg==",
    form: "dual",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "filesystem"],
    description: "Match files using shell glob patterns.",
  },
  {
    name: "cross-spawn",
    version: "7.0.6",
    integrity: "sha512-uV2QOWP2nWzsy2aMp8aRibhi9dlzF5Hgh5SHaB9OiTGEyDTiJJyx0uy51QXdyWbtAHNua4XJzUKca3OzKUd3vA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: true, lifecycleScripts: false },
    tags: ["spawn-legitimate", "child-process"],
    description: "Cross-platform child_process.spawn replacement.",
  },
  {
    name: "fs-extra",
    version: "11.2.0",
    integrity: "sha512-PmDi3uwK5nFuXh7XDTlVnS17xJS7vW36is2+w3xcv8SVxiB4NyATf4ctkVY5bkSjX0Y4nbvZCq1/EjtEyr9ktw==",
    form: "cjs",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "filesystem"],
    description: "node fs module helpers (copy, move, ensureDir, etc.).",
  },
  {
    name: "mkdirp",
    version: "3.0.1",
    integrity: "sha512-+NsyUUAZDmo6YVHzL/stxSu3t9YS1iljliy3BSDrXJ/dkn1KYdmtZODGGjLcc9XLgVVpH4KshHB8XmZgMhaBXg==",
    form: "dual",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "filesystem", "tiny"],
    description: "Recursive mkdir, like `mkdir -p`.",
  },

  // ── Tier 3: heavier, network/crypto-using ─────────────────────────────
  {
    name: "axios",
    version: "1.7.9",
    integrity: "sha512-LhLcE7Hbiryz8oMDdDptSrWowmB4Bl6RCt6sIJKpRB4XtVf0iEgewX3au/pJqm+Py1kCASkb/FFKjxQaLtxJvw==",
    form: "cjs",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "http"],
    description: "Promise-based HTTP client.",
  },
  {
    name: "node-fetch",
    version: "2.7.0",
    integrity: "sha512-c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==",
    form: "cjs",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "http"],
    description: "Bring `window.fetch` to Node.js (last CJS major).",
  },
  {
    name: "bcryptjs",
    version: "2.4.3",
    integrity: "sha512-V/Hy/X9Vt7f3BbPJEi8BdVFMByHi+jNXrYkW3huaybV/kQ0KJg0Y6PkEMbn+zeT+i+SiKZ/HMqJGIIt4LZDqNQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["crypto-legitimate", "auth"],
    description: "Pure-JS bcrypt implementation.",
  },
  {
    name: "jsonwebtoken",
    version: "9.0.2",
    integrity: "sha512-PRp66vJ865SSqOlgqS8hujT5U4AOgMfhrwYIuIhfKaoSCZcirrmASQr8CX7cUg+RMih+hgznrjp99o+W4pJLHQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["crypto-legitimate", "auth", "jwt"],
    description: "JSON Web Token implementation.",
  },
  {
    name: "zod",
    version: "3.23.8",
    integrity: "sha512-XBx9AXhXktjUqnepgTiE5flcKIYWi/rme0Eaj+5Y0lftuGBq+jyRu/md4WnuxqgP1ubdpNCsYEYPxrzVHD8d6g==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "validation"],
    description: "TypeScript-first schema validation.",
  },
  {
    name: "joi",
    version: "17.13.3",
    integrity: "sha512-otDA4ldcIx+ZXsKHWmp0YizCweVRZG96J10b0FevjfuncLO1oX59THoAmHkNubYJ+9gWsYsp5k8v4ib6oDv1fA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "validation"],
    description: "Schema validation for JavaScript.",
  },
  {
    name: "p-limit",
    version: "5.0.0",
    integrity: "sha512-/Eaoq+QyLSiXQ4lyYV23f14mZRQcXnxfHrN0vCai+ak9G0pp9iEQukIIZq5NccEvwRB8PUnZT0KsOoDCINS1qQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "concurrency", "tiny"],
    description: "Run multiple promise-returning & async functions with concurrency limit.",
  },

  // ── Tier 3b: expanded SAFE controls for v1.1 precision ───────────────
  {
    name: "nanoid",
    version: "5.1.16",
    integrity: "sha512-kVrnsrJqMR8+oLJnGEmSWw9BivK5mt7H3FZatVRjrc5wGqFYuBxX1yG7+A7Gi5AefkX6t/oCkizcQgpu0cY1dQ==",
    form: "esm",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["pure", "crypto-legitimate", "id"],
    description: "Tiny secure URL-friendly unique string ID generator.",
  },
  {
    name: "fast-deep-equal",
    version: "3.1.3",
    integrity: "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "tiny", "equality"],
    description: "Fast deep equality comparison utility.",
  },
  {
    name: "camelcase",
    version: "9.0.0",
    integrity: "sha512-TO9xmyXTZ9HUHI8M1OnvExxYB0eYVS/1e5s7IDMTAoIcwUd+aNcFODs6Xk83mobk0velyHFQgA1yIrvYc6wclw==",
    form: "esm",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "string"],
    description: "Convert dash/dot/underscore/space-separated strings to camelCase.",
  },
  {
    name: "kleur",
    version: "4.1.5",
    integrity: "sha512-o+NO+8WrRiQEE4/7nwRJhN1HWpVmJm511pBHUxPLtp0BUISzlBplORYSmTclCnJvQq2tKu/sgl3xVpkc7ZWuQQ==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "terminal", "tiny"],
    description: "Terminal color formatting utility.",
  },
  {
    name: "dayjs",
    version: "1.11.21",
    integrity: "sha512-98IT+HOahAisibz/yjKbzuOBwYcjJ7BCLPzARyHiyEBmRz4fatF+KPJszEHXsGYjUG234aH/cOjW1wwTbKUZlA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "date"],
    description: "Small immutable date/time library.",
  },
  {
    name: "yargs",
    version: "18.0.0",
    integrity: "sha512-4UEqdc2RYGHZc7Doyqkrqiln3p9X2DZVxaGbwhn2pi7MrRagKaOcIKe8L3OxYcbhXLgLFUS3zAYuQjKBQgmuNg==",
    form: "dual",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "parser"],
    description: "CLI argument parser with command and help generation.",
  },
  {
    name: "minimist",
    version: "1.2.8",
    integrity: "sha512-2yyAR8qBkN3YuheJanUpWC5U3bb5osDywNB8RzDVlDwDHbocAJveqqj1u8+SVD7jkWT4yvsHCpWqqWqAxb0zCA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "parser", "tiny"],
    description: "Minimal command-line argument parser.",
  },
  {
    name: "arg",
    version: "5.0.2",
    integrity: "sha512-PYjyFOLKQ9y57JvQ6QLo8dAgNqswh8M1RMJYdQduT6xbWSgK36P/Z/v+p888pM69jMMfS8Xd8F6I1kQ/I9HUGg==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "parser", "tiny"],
    description: "Simple argument parser.",
  },
  {
    name: "meow",
    version: "14.1.0",
    integrity: "sha512-EDYo6VlmtnumlcBCbh1gLJ//9jvM/ndXHfVXIFrZVr6fGcwTUyCTFNTLCKuY3ffbK8L/+3Mzqnd58RojiZqHVw==",
    form: "esm",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "parser"],
    description: "CLI app helper for arguments, help text, and metadata.",
  },
  {
    name: "ora",
    version: "9.4.1",
    integrity: "sha512-6VlU9MLXbjVQD04AZCMX28hVtA5bUoadvUqO76MUCVA0ilwJbMiHsITRPfyVm6p/BC0Av/BXMujx39WCe1LEqw==",
    form: "esm",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "terminal"],
    description: "Terminal spinner utility for command-line applications.",
  },
  {
    name: "inquirer",
    version: "14.0.2",
    integrity: "sha512-VsSx1JneSNp3ld1veMTLe+UDcUD8Tw2/jjOthhkX3/IX2q+xHhVELifeb/hsb1fBw31pabEPNUf/xUOyb+KZjA==",
    form: "esm",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["cli", "prompts"],
    description: "Interactive command-line prompt toolkit.",
  },
  {
    name: "rimraf",
    version: "6.1.3",
    integrity: "sha512-LKg+Cr2ZF61fkcaK1UdkH2yEBBKnYjTyWzTJT6KNPcSPaiT7HSdhtMXQuN5wkTX0Xu72KQ1l8S42rlmexS2hSA==",
    form: "dual",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "filesystem"],
    description: "Cross-platform recursive file removal utility.",
  },
  {
    name: "execa",
    version: "9.6.1",
    integrity: "sha512-9Be3ZoN4LmYR90tUoVu2te2BsbzHfhJyfEiAVfz7N5/zv+jduIfLrV2xdQXOHbaD6KgpGdO9PRPM1Y4Q9QkPkA==",
    form: "esm",
    profile: { network: false, fs: false, crypto: false, spawn: true, lifecycleScripts: false },
    tags: ["spawn-legitimate", "child-process"],
    description: "Process execution library for Node.js.",
  },
  {
    name: "chokidar",
    version: "5.0.0",
    integrity: "sha512-TQMmc3w+5AxjpL8iIiwebF73dRDF4fBIieAqGn9RGCWaEVwQ6Fb2cGe31Yns0RRIzii5goJ1Y7xbMwo1TxMplw==",
    form: "esm",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "watcher"],
    description: "File watching library.",
  },
  {
    name: "find-up",
    version: "8.0.0",
    integrity: "sha512-JGG8pvDi2C+JxidYdIwQDyS/CgcrIdh18cvgxcBge3wSHRQOrooMD3GlFBcmMJAN9M42SAZjDp5zv1dglJjwww==",
    form: "esm",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "filesystem"],
    description: "Find a file or directory by walking up parent directories.",
  },
  {
    name: "tar",
    version: "7.5.19",
    integrity: "sha512-4LeEWl96twnS2Q7Bz4MGqgazLqO+hJN63GZxXoIqh1T3VweYD997gbU1ItNsQafqqXTXd5WFyFdReLtwvRBNiw==",
    form: "cjs",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["fs-legitimate", "archive"],
    description: "Tar archive creation and extraction library.",
  },
  {
    name: "got",
    version: "15.1.0",
    integrity: "sha512-DG+DAAkRtno+oDr/GBsliAkhN9+zczOPM5qXk3efDZY3qvyRnZU+NwQlb/IOY6cSnxxTR9z3aHCcShJyjb0hJA==",
    form: "esm",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "http"],
    description: "Human-friendly HTTP request library.",
  },
  {
    name: "undici",
    version: "8.6.0",
    integrity: "sha512-l2FlC6I510GawyEd1qgcE/okihKrzy+BRTEBlu6T0fdbM9m5yxtIH5Oa3ysRsH0zC4EhmWUEaSDsy2QngBeRlw==",
    form: "cjs",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "http"],
    description: "HTTP client used by Node.js.",
  },
  {
    name: "ky",
    version: "2.0.2",
    integrity: "sha512-/GmXpo9F9W+f8n4Ivr2iH+7h7wL7jLbLKWkMlpflcCRb6kGjBfTlASEXaZ9qUgNTn4VgS0P2pwxxzQ4EM6Ulgg==",
    form: "esm",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "http", "browser"],
    description: "Tiny HTTP client based on Fetch.",
  },
  {
    name: "graphql-request",
    version: "7.4.0",
    integrity: "sha512-xfr+zFb/QYbs4l4ty0dltqiXIp07U6sl+tOKAb0t50/EnQek6CVVBLjETXi+FghElytvgaAWtIOt3EV7zLzIAQ==",
    form: "esm",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "graphql"],
    description: "Minimal GraphQL request client.",
  },
  {
    name: "ws",
    version: "8.21.0",
    integrity: "sha512-Vsp28b7DRcimFQvrqu2Wek3z1iYxDCWqHYB8Qsnk/S4RfaCQzPGPyBNuVjJV3cd6UiKtUtp6sNM77gWvzcCH+g==",
    form: "cjs",
    profile: { network: true, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["network-legitimate", "websocket"],
    description: "WebSocket client and server library.",
  },
  {
    name: "esbuild",
    version: "0.28.1",
    integrity: "sha512-HrJrvZv5ayxBzPfwphOoNzkzOIIlifzk0KJrGK2c8R4+LKpMtpYLQeUdjnwjWv/LZlkH2laZk+4w78pi99D4Vw==",
    form: "cjs",
    profile: { network: false, fs: true, crypto: false, spawn: true, lifecycleScripts: true },
    tags: ["build-tool", "native", "lifecycle-legitimate"],
    description: "JavaScript bundler and minifier with a native binary.",
  },
  {
    name: "rollup",
    version: "4.62.2",
    integrity: "sha512-RFnrW4lhXA3s3eqHDZvN654g8OTjzRfqpIRJYczCGB6HzphckVAi/Qh4tbPUbRuDi7s1Llv8g/NspLkttY3gTA==",
    form: "dual",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["build-tool", "bundler"],
    description: "JavaScript module bundler.",
  },
  {
    name: "vite",
    version: "8.1.3",
    integrity: "sha512-Ds+gBRbj0lwRO2Y5hwnUBdxSwlAve9LeRyU4sNnAr0ewW0gWF0n5bgXgUzbgZ49MV9BVUAQUFYVcDUcilUExMA==",
    form: "esm",
    profile: { network: false, fs: true, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["build-tool", "dev-server"],
    description: "Frontend build tool and dev server.",
  },
  {
    name: "postcss",
    version: "8.5.16",
    integrity: "sha512-vuwillviilfKZsg0VGj5R/YwwcHx4SLsIOI/7K6mQkWx+l5cUHTjj5g0AasTBcyXsbfTgrwsUNmVUb5xVwyPwg==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["build-tool", "css"],
    description: "CSS parser and transformer framework.",
  },
  {
    name: "autoprefixer",
    version: "10.5.2",
    integrity: "sha512-rD5t5DwOjJdmSORcTq64j8MawTC+tbQ+HHqjR4NDumamy/ambn1UJrlKL+KdwujWxMkFjPM3pPHOEA9tl4767Q==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["build-tool", "css"],
    description: "PostCSS plugin that adds vendor prefixes.",
  },
  {
    name: "jose",
    version: "6.2.3",
    integrity: "sha512-YYVDInQKFJfR/xa3ojUTl8c2KoTwiL1R5Wg9YCydwH0x0B9grbzlg5HC7mMjCtUJjbQ/YnGEZIhI5tCgfTb4Hw==",
    form: "esm",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["crypto-legitimate", "auth"],
    description: "JOSE standards implementation for JWT, JWS, JWE, JWK, and more.",
  },
  {
    name: "tweetnacl",
    version: "1.0.3",
    integrity: "sha512-6rt+RN7aOi1nGMyC4Xa5DdYiukl2UWCbcJft7YhxReBGQD7OAM8Pbxw6YMo4r2diNEA8FEmu32YOn9rhaiE5yw==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: false },
    tags: ["crypto-legitimate"],
    description: "Port of the NaCl cryptographic library.",
  },
  {
    name: "ajv",
    version: "8.20.0",
    integrity: "sha512-Thbli+OlOj+iMPYFBVBfJ3OmCAnaSyNn4M1vz9T6Gka5Jt9ba/HIR56joy65tY6kx/FCF5VXNB819Y7/GUrBGA==",
    form: "cjs",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: false },
    tags: ["pure", "validation"],
    description: "JSON Schema validator.",
  },

  // ── Tier 4: native bindings — runtime-evidence verifiability is N/A ──
  {
    name: "bcrypt",
    version: "5.1.1",
    integrity: "sha512-AGBHOG5hPYZ5Xl9KXzU5iKq9516yEmvCKDg3ecP5kX2aB6UqTeXZxk2ELnDgDm6BQSMlLt9rDB4LoSMx0rYwww==",
    form: "native-binding",
    profile: { network: false, fs: false, crypto: true, spawn: false, lifecycleScripts: true },
    tags: ["native", "crypto-legitimate", "lifecycle-legitimate"],
    description: "Native bcrypt binding; has install lifecycle script.",
  },
  {
    name: "bufferutil",
    version: "4.0.8",
    integrity: "sha512-4T53u4PdgsXqKaIctwF8ifXlRTTmEPJ8iEPWFdGZvcf7sbwYo6FKFEX9eNNAnzFZ7EzJAQ3CJeOtCRA4rDp7Pw==",
    form: "native-binding",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: true },
    tags: ["native", "websocket-helper"],
    description: "Native helper for the `ws` websocket library.",
  },
  {
    name: "tree-sitter",
    version: "0.21.1",
    integrity: "sha512-7dxoA6kYvtgWw80265MyqJlkRl4yawIjO7S5MigytjELkX43fV2WsAXzsNfO7sBpPPCF5Gp0+XzHk0DwLCq3xQ==",
    form: "native-binding",
    profile: { network: false, fs: false, crypto: false, spawn: false, lifecycleScripts: true },
    tags: ["native", "parser"],
    description: "Native incremental parser bindings.",
  },
];

/** Number of seeds in the catalogue — handy for sanity checks. */
export const SEED_COUNT = SEEDS.length;
