# CLASS MAP — attestations.py, the World ID trust boundary.
# Seam: WorldVerifier takes an injected httpx.AsyncClient pointed at a stub; no
# network. The signal hash is pinned against vectors generated by the REAL
# reference implementation (idkit-core@4.2.2 dist/hashing.js under node).
#
# Hashing:  A1 the port matches the JS reference byte-for-byte, including the
#              three inputs that distinguish hex-decoding from UTF-8 encoding
#           A2 signal composition refuses to build an unbound signal
# Verify:   A3 happy path → nullifier + tier + presence
#           A4 World says failure → AttestationError, never partial acceptance
#           A5 signal_hash mismatch → refused (the replay defence)
#           A6 NO signal_hash at all → refused (unbound proof is the same hole)
#           A7 action mismatch → refused (a different nullifier namespace)
#           A8 missing user presence → refused when required
#           A9 no nullifier → refused
#           A10 unconfigured → refused before any request is made
# Tiers:    A11 identity_attested drives the tier; absence is tier 1, not failure
# Envelope: A12 identity attribute VALUES can never be published
#           A13 non-boolean assertions refused
#           A14 environment is recorded so staging is never mistakable for real
#
# Blackbox: drives hash_signal / release_signal / assign_tier / build_envelope /
# WorldVerifier.verify — the module's public surface.

import httpx
import pytest

from npmguard.attestations import (
    TIER_HUMAN,
    TIER_IDENTITY,
    TIER_JURISDICTION,
    AttestationError,
    VerifiedAttestation,
    WorldVerifier,
    artifact_digest,
    assign_tier,
    build_envelope,
    hash_signal,
    release_signal,
    sign_rp_request,
)
from npmguard.config import Settings

# Generated by running the published idkit-core@4.2.2 `hashSignal` under node.
# Regenerate with: node -e "import('./dist/hashing.js').then(m=>console.log(m.hashSignal(X)))"
REFERENCE_VECTORS = {
    "npmguard:v1:lodash@4.17.21:sha512-abc:12345": (
        "0x00484201898c489a8c7cc5c1a4974a2f1cdb6ab10805639f57b28e3f059cf6cc"
    ),
    "": "0x00c5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a4",
    "hello world": "0x0047173285a8d7341e5e972fc677286384f802f8ef42a5ec5f03bbfa254cb01f",
    # valid hex → decoded as BYTES
    "0xdeadbeef": "0x00d4fd4e189132273036449fc9e11198c739161b4c0116a9a2dccdfa1c492006",
    # invalid hex chars → UTF-8
    "0xZZZ": "0x007d60fc96e90e676ff51f791abc59dd89698d4c83d8cf1d9c6d6a5b0145dc75",
    # odd length → UTF-8
    "0xabc": "0x00851bb152e67e6c958ab7da1431fcaed09ce0efc598885f69a750b3b4b81fc1",
    "npmguard:v1:@scope/pkg@1.0.0-rc.1:sha512-Zm9v:99": (
        "0x00edfe989d8145b22064e993ad8bb16b7650e823c8edda133454a49aa1214aa8"
    ),
}

SIGNAL = "npmguard:v1:lodash@4.17.21:sha512-abc:12345"
SIGNAL_HASH = REFERENCE_VECTORS[SIGNAL]
NULLIFIER = "0xnull1f1er"


def _settings(**overrides) -> Settings:
    return Settings(
        _env_file=None,
        world_app_id="app_test",
        world_rp_id="rp_test",
        world_signing_key="0f" * 32,
        world_api_base="https://world.test/api",
        **overrides,
    )


def _verify_with(body: dict) -> WorldVerifier:
    return WorldVerifier(
        _settings(),
        client=httpx.AsyncClient(
            transport=httpx.MockTransport(lambda request: httpx.Response(200, json=body))
        ),
    )


# --- A1/A2: signal ---------------------------------------------------------


@pytest.mark.parametrize(("signal", "expected"), sorted(REFERENCE_VECTORS.items()))
def test_hash_signal_matches_the_reference_implementation(signal, expected) -> None:
    """World's hashSignal ships only as JS and is unspecified in the docs, so
    this port is pinned against the real thing. The three 0x-prefixed cases are
    the ones an integrator gets wrong: a string that LOOKS like hex is decoded as
    bytes, one that only looks like it is not."""
    assert hash_signal(signal) == expected


def test_a_signal_cannot_be_built_without_every_binding() -> None:
    """Each component closes a replay: version+integrity bind the artifact, the
    GitHub user id binds the authenticated session. A missing one is a hole, not
    a default."""
    for missing in ("package_name", "version", "integrity", "github_user_id"):
        parts = {
            "package_name": "lodash",
            "version": "4.17.21",
            "integrity": "sha512-abc",
            "github_user_id": "12345",
        }
        parts[missing] = ""
        with pytest.raises(AttestationError, match=missing):
            release_signal(**parts)


def test_the_signal_is_versioned_and_carries_every_binding() -> None:
    signal = release_signal(
        package_name="lodash", version="4.17.21", integrity="sha512-abc", github_user_id="12345"
    )
    assert signal == SIGNAL
    assert signal.startswith("npmguard:v1:")


# --- A3-A10: verification ---------------------------------------------------


async def test_a_valid_proof_yields_a_bound_present_human() -> None:
    verified = await _verify_with(
        {
            "success": True,
            "action": "attest-npm-release",
            "nullifier": NULLIFIER,
            "environment": "staging",
            "user_presence_completed": True,
            "results": [{"signal_hash": SIGNAL_HASH}],
        }
    ).verify({}, expected_signal=SIGNAL)
    assert verified.nullifier == NULLIFIER
    assert verified.tier == TIER_HUMAN
    assert verified.user_presence is True
    assert verified.environment == "staging"


async def test_a_document_credential_reaches_tier_2_without_disclosing_anything() -> None:
    """A passport-issued proof is document-backed by construction.

    `issuer_schema_id` is a property of the credential that produced the proof,
    so the document tier is established without requesting a single identity
    attribute — no name, no document number, no nationality, not even an age
    assertion. This is the strongest form of the minimization claim: there is
    nothing to leak because nothing was asked for.
    """
    verified = await _verify_with(
        {
            "success": True,
            "action": "attest-npm-release",
            "environment": "staging",
            "user_presence_completed": True,
            "responses": [
                {"signal_hash": SIGNAL_HASH, "nullifier": NULLIFIER, "issuer_schema_id": 9303}
            ],
        }
    ).verify({}, expected_signal=SIGNAL)
    assert verified.tier == TIER_IDENTITY
    assert verified.document_backed is True
    # ...and World was never asked to attest attributes, so it did not.
    assert verified.identity_attested is False


async def test_an_orb_proof_stays_tier_1_and_is_not_called_document_backed() -> None:
    """The other half of the pair: a proof-of-human credential is schema 1, and
    must never be graded as though a document backed it."""
    verified = await _verify_with(
        {
            "success": True,
            "action": "attest-npm-release",
            "environment": "staging",
            "user_presence_completed": True,
            "responses": [
                {"signal_hash": SIGNAL_HASH, "nullifier": NULLIFIER, "issuer_schema_id": 1}
            ],
        }
    ).verify({}, expected_signal=SIGNAL)
    assert verified.tier == TIER_HUMAN
    assert verified.document_backed is False


async def test_a_legacy_proof_records_the_protocol_it_was_made_under() -> None:
    """A v3 proof may be allowed, but it must never be indistinguishable from a
    v4 one after the fact."""
    verified = await _verify_with(
        {
            "success": True,
            "protocol_version": "3.0",
            "action": "attest-npm-release",
            "environment": "staging",
            "user_presence_completed": True,
            "results": [{"signal_hash": SIGNAL_HASH, "nullifier": NULLIFIER}],
        }
    ).verify({}, expected_signal=SIGNAL)
    assert verified.protocol_version == "3.0"
    assert verified.tier == TIER_HUMAN


async def test_a_rejected_proof_is_never_partially_accepted() -> None:
    with pytest.raises(AttestationError, match="all_verifications_failed"):
        await _verify_with(
            {"success": False, "code": "all_verifications_failed"}
        ).verify({}, expected_signal=SIGNAL)


async def test_a_rejection_carries_worlds_own_explanation() -> None:
    """A bare code is not a diagnosis.

    A real `validation_error` cost real debugging time because the reason —
    which field World could not read — was dropped on the floor and the operator
    saw only "World rejected the proof". Whatever World says about why must
    reach the operator.
    """
    with pytest.raises(AttestationError) as caught:
        await _verify_with(
            {
                "success": False,
                "code": "validation_error",
                "detail": "responses: field required",
            }
        ).verify({}, expected_signal=SIGNAL)
    assert "validation_error" in str(caught.value)
    assert "responses: field required" in str(caught.value)


async def test_a_signal_hash_for_another_artifact_is_refused() -> None:
    """THE replay defence: a proof minted for one tarball must be worthless for
    any other. Without this the whole design is decorative."""
    other = hash_signal("npmguard:v1:lodash@4.17.22:sha512-evil:12345")
    with pytest.raises(AttestationError, match="does not match this release"):
        await _verify_with(
            {
                "success": True,
                "nullifier": NULLIFIER,
                "user_presence_completed": True,
                "results": [{"signal_hash": other}],
            }
        ).verify({}, expected_signal=SIGNAL)


async def test_a_proof_with_no_signal_hash_is_refused() -> None:
    """An unbound proof is the same hole as a mismatched one — it authorizes
    everything. This is the shape World's IdentityCheck preset would produce,
    since it accepts no signal (finding D-1)."""
    with pytest.raises(AttestationError, match="not artifact-bound"):
        await _verify_with(
            {
                "success": True,
                "nullifier": NULLIFIER,
                "user_presence_completed": True,
                "results": [{"identifier": "document"}],
            }
        ).verify({}, expected_signal=SIGNAL)


async def test_a_proof_for_a_different_action_is_refused() -> None:
    """The action scopes the nullifier, so another action is another pseudonym
    namespace — admitting it would let an unrelated app's proof pose as a
    publisher identity here."""
    with pytest.raises(AttestationError, match="does not match"):
        await _verify_with(
            {
                "success": True,
                "action": "some-other-app-action",
                "nullifier": NULLIFIER,
                "user_presence_completed": True,
                "results": [{"signal_hash": SIGNAL_HASH}],
            }
        ).verify({}, expected_signal=SIGNAL)


async def test_a_proof_without_fresh_presence_is_refused() -> None:
    """Fresh liveness is what a worm cannot fake. A proof without it is exactly
    the automated publish we exist to catch."""
    with pytest.raises(AttestationError, match="user-presence"):
        await _verify_with(
            {
                "success": True,
                "nullifier": NULLIFIER,
                "user_presence_completed": False,
                "results": [{"signal_hash": SIGNAL_HASH}],
            }
        ).verify({}, expected_signal=SIGNAL)


async def test_a_verified_proof_without_a_nullifier_is_refused() -> None:
    with pytest.raises(AttestationError, match="no nullifier"):
        await _verify_with(
            {
                "success": True,
                "user_presence_completed": True,
                "results": [{"signal_hash": SIGNAL_HASH}],
            }
        ).verify({}, expected_signal=SIGNAL)


async def test_an_unconfigured_engine_refuses_before_any_request() -> None:
    called = False

    def handler(request):
        nonlocal called
        called = True
        return httpx.Response(200, json={"success": True})

    verifier = WorldVerifier(
        Settings(_env_file=None), client=httpx.AsyncClient(transport=httpx.MockTransport(handler))
    )
    assert not verifier.enabled
    with pytest.raises(AttestationError, match="not configured"):
        await verifier.verify({}, expected_signal=SIGNAL)
    assert not called, "an unconfigured engine must not talk to World at all"


async def test_a_non_json_reply_is_a_typed_error() -> None:
    verifier = WorldVerifier(
        _settings(),
        client=httpx.AsyncClient(
            transport=httpx.MockTransport(lambda r: httpx.Response(502, text="<html>bad gateway"))
        ),
    )
    with pytest.raises(AttestationError, match="non-JSON"):
        await verifier.verify({}, expected_signal=SIGNAL)


# --- A11: tiers -------------------------------------------------------------


def test_identity_attestation_drives_the_tier() -> None:
    """Tier 1 is a full-strength security claim, not a failure: proof of human
    bound to the artifact is what stops the worm. The document tier is assurance
    layered on top."""
    assert assign_tier(identity_attested=False) == TIER_HUMAN
    assert assign_tier(identity_attested=True) == TIER_IDENTITY
    assert assign_tier(identity_attested=True, has_jurisdiction=True) == TIER_JURISDICTION


async def test_identity_attested_is_carried_through_verification() -> None:
    verified = await _verify_with(
        {
            "success": True,
            "nullifier": NULLIFIER,
            "user_presence_completed": True,
            "identity_attested": True,
            "results": [{"signal_hash": SIGNAL_HASH}],
        }
    ).verify({}, expected_signal=SIGNAL)
    assert verified.identity_attested is True
    assert verified.tier == TIER_IDENTITY


# --- A12-A14: the public envelope -------------------------------------------


def _verified(**overrides) -> VerifiedAttestation:
    base = {
        "nullifier": NULLIFIER,
        "tier": TIER_IDENTITY,
        "identity_attested": True,
        "user_presence": True,
        "environment": "staging",
        "action": "attest-npm-release",
    }
    base.update(overrides)
    return VerifiedAttestation(**base)


def _envelope(**overrides):
    kwargs = {
        "package_name": "lodash",
        "version": "4.17.21",
        "integrity": "sha512-abc",
        "verified": _verified(),
        "attested_at": "2026-07-25T12:00:00Z",
        "assertions": {"minimum_age>=18": True, "document_backed": True},
        "verifier": "0xrelayer",
    }
    kwargs.update(overrides)
    return build_envelope(**kwargs)


def test_the_envelope_publishes_assertions_not_identity() -> None:
    """The envelope goes to public, immutable storage. It must say WHAT was
    proven without saying WHO — a real-name registry of open-source maintainers
    is a target, and pseudonymity costs the security property nothing."""
    envelope = _envelope()
    assert envelope["nullifier"] == NULLIFIER
    assert envelope["assertions"] == {"document_backed": True, "minimum_age>=18": True}
    blob = repr(envelope)
    for leak in ("full_name", "document_number", "passport", "nationality"):
        assert leak not in blob


@pytest.mark.parametrize(
    "attribute", ["full_name", "document_number", "nationality", "issuing_country", "document_type"]
)
def test_identity_attribute_values_can_never_be_published(attribute) -> None:
    """Enforced by the serializer, not by review — this is the data-minimization
    promise made to every maintainer who attests."""
    with pytest.raises(AttestationError, match="never be published"):
        _envelope(assertions={attribute: True})


def test_assertions_must_be_booleans() -> None:
    """A string assertion is an attribute value wearing a boolean's name."""
    with pytest.raises(AttestationError, match="booleans"):
        _envelope(assertions={"minimum_age": "34"})


def test_the_envelope_records_which_world_environment_produced_it() -> None:
    """A staging proof carries no real-world assurance. Recording the
    environment is what stops a demo attestation from later reading as a real
    one — the record is immutable, so it has to be self-describing."""
    assert _envelope()["environment"] == "staging"
    assert _envelope(verified=_verified(environment="production"))["environment"] == "production"


def test_the_artifact_digest_is_derived_from_npm_integrity() -> None:
    """Fixed width for the chain row, and recomputable by anyone holding the
    package metadata — so a third party can check the row refers to the tarball
    npm actually served."""
    digest = artifact_digest("sha512-abc")
    assert digest.startswith("0x") and len(digest) == 66
    assert digest == _envelope()["artifactDigest"]
    assert artifact_digest("sha512-abc") != artifact_digest("sha512-abd")
    with pytest.raises(AttestationError):
        artifact_digest("")


# --- A15: the RP signature --------------------------------------------------
# Ported from @worldcoin/idkit-server@1.1.1 (signRequest). Undocumented and
# Node-only — the reference refuses to run outside Node — so these vectors were
# generated by executing the real implementation and are the only thing keeping
# the port honest.

RP_NONCE_SEED = bytes([7]) * 32
RP_NONCE = "007b062064095a97578a0f0cf535dd321f48f102ebc87a8ca16dd4b4c5fc6c4d"
RP_CREATED_AT = 1780000000
RP_EXPIRES_AT = 1780000300
RP_MESSAGE_WITH_ACTION = (
    "01007b062064095a97578a0f0cf535dd321f48f102ebc87a8ca16dd4b4c5fc6c4d"
    "000000006a18a500000000006a18a62c"
    "0036657751dde2a289beff68863648cdfdd2c2db40ee25005f719402bc5e1306"
)
RP_MESSAGE_NO_ACTION = (
    "01007b062064095a97578a0f0cf535dd321f48f102ebc87a8ca16dd4b4c5fc6c4d"
    "000000006a18a500000000006a18a62c"
)


def test_the_rp_signature_message_matches_the_reference() -> None:
    """Byte layout: version | nonce(32) | created_at(u64 BE) | expires_at(u64 BE)
    | hashToField(action). One wrong offset and every proof request is rejected
    as an invalid RP signature, with no hint as to why."""
    from npmguard.attestations import _hash_to_field, rp_signature_message

    nonce = _hash_to_field(RP_NONCE_SEED)
    assert nonce.hex() == RP_NONCE
    assert (
        rp_signature_message(nonce, RP_CREATED_AT, RP_EXPIRES_AT, "attest-npm-release").hex()
        == RP_MESSAGE_WITH_ACTION
    )
    assert (
        rp_signature_message(nonce, RP_CREATED_AT, RP_EXPIRES_AT, None).hex()
        == RP_MESSAGE_NO_ACTION
    )


def test_the_rp_signature_recovers_to_the_signing_key() -> None:
    """EIP-191 over secp256k1 with v = recovery + 27. Verified by recovering the
    address, which is what World's side will do."""
    from eth_account import Account
    from eth_account.messages import encode_defunct

    from npmguard.attestations import (
        RP_SIGNATURE_TTL_SECONDS,
        rp_signature_message,
        sign_rp_request,
    )

    key = "11" * 32
    context = sign_rp_request(
        signing_key=key, action="attest-npm-release", now=RP_CREATED_AT, nonce_seed=RP_NONCE_SEED
    )
    assert context["nonce"] == "0x" + RP_NONCE
    assert context["createdAt"] == RP_CREATED_AT
    assert context["expiresAt"] == RP_CREATED_AT + RP_SIGNATURE_TTL_SECONDS

    signature = bytes.fromhex(context["sig"][2:])
    assert len(signature) == 65, "65 bytes: r || s || (recovery + 27)"
    assert signature[64] in (27, 28)

    message = rp_signature_message(
        bytes.fromhex(RP_NONCE), RP_CREATED_AT, context["expiresAt"], "attest-npm-release"
    )
    recovered = Account.recover_message(encode_defunct(message), signature=signature)
    assert recovered == Account.from_key(key).address


def test_a_malformed_signing_key_is_refused() -> None:
    """Fails loudly at signing time rather than producing a signature World will
    silently reject."""
    for bad in ("", "0x1234", "zz" * 32):
        with pytest.raises(AttestationError, match="signing key"):
            sign_rp_request(signing_key=bad, action="a", now=RP_CREATED_AT)


def test_each_request_gets_a_fresh_nonce() -> None:
    """A reused nonce is a replayable proof request — World rejects duplicates
    (DuplicateNonce), and relying on that would be trusting the far side to
    enforce our freshness."""
    first = sign_rp_request(signing_key="11" * 32, action="a", now=RP_CREATED_AT)
    second = sign_rp_request(signing_key="11" * 32, action="a", now=RP_CREATED_AT)
    assert first["nonce"] != second["nonce"]
