# CLASS MAP — panel.crypto (seam: `crypto.get_settings` monkeypatched to inject
# the 32-byte hex key; pure in-memory AES-256-GCM, no DB/HTTP)
# Unit: encrypt(plaintext) / decrypt(blob) and the TokenCryptoError contract.
# Axes: plaintext shape (ascii / unicode / empty) × key (correct / wrong / missing)
#       × blob health (well-formed / wrong-part-count / bad-base64 / bad-iv-len /
#         bad-tag-len / tampered-ciphertext) × origin (this module / TS-generated golden)
#   C1  round-trip: ascii, unicode, and empty plaintext survive encrypt→decrypt
#   C2  wire shape: blob is exactly 3 dot-joined parts, each valid base64;
#       decoded IV == 12 bytes, tag == 16 bytes
#   C3  confidentiality: ciphertext bytes never equal the plaintext, and the
#       random IV makes two encryptions of the same plaintext differ
#   C4  malformed blob — wrong part count (2 or 4 parts) → TokenCryptoError
#   C5  malformed blob — a part is not valid base64 → TokenCryptoError
#   C6  malformed blob — decoded IV / tag has the wrong length → TokenCryptoError
#   C7  wrong key → auth-tag failure raises TokenCryptoError (not plaintext)
#   C8  tamper: flipping one ciphertext byte → auth-tag failure
#   C9  key absent (encryption_key is None) → TokenCryptoError on encrypt & decrypt
#   C10 INTEROP: a blob produced by the TS/node `crypto.ts` (createCipheriv
#       aes-256-gcm, [iv,tag,ct] base64-joined) decrypts to the exact plaintext,
#       proving the byte-for-byte format match across implementations
#   C11 no plaintext leak: TokenCryptoError messages never contain the plaintext
# Adversarial pass — "which dimension is missing?": the key axis was split into
#   correct / wrong / MISSING (C9) and confidentiality (C3) was added so a broken
#   no-op "encrypt" that returned base64(plaintext) with a valid shape can't pass.
import base64
import types

import pytest

from npmguard.panel import crypto
from npmguard.panel.crypto import TokenCryptoError

# A 32-byte key (64 hex chars) for the round-trip / negative classes.
KEY_A = "aa" * 32
# A different valid key, for the wrong-key class.
KEY_B = "bb" * 32

# --- TS/node cross-implementation golden (C10) -------------------------------
# Generated by node's crypto.ts equivalent:
#   key  = 00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff
#   iv   = 0102030405060708090a0b0c (fixed for a deterministic golden)
#   createCipheriv("aes-256-gcm", key, iv) over the plaintext below,
#   blob = [iv, tag, ciphertext].map(b => b.toString("base64")).join(".")
INTEROP_KEY = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff"
INTEROP_PLAINTEXT = "gho_exampleOAuthToken_ABC123"
INTEROP_BLOB = (
    "AQIDBAUGBwgJCgsM.UE13k6CSQPN116mvJVeLPQ==.HRpq/41vxCyalN6OLZpreifxyJJZrqcBb6PGnA=="
)


def _use_key(monkeypatch, key_hex: str | None) -> None:
    """Move the key through the module seam (TESTING.md: observable seam)."""
    monkeypatch.setattr(
        crypto, "get_settings", lambda: types.SimpleNamespace(encryption_key=key_hex)
    )


@pytest.fixture
def key_a(monkeypatch):
    _use_key(monkeypatch, KEY_A)


@pytest.mark.parametrize(
    "plaintext",
    ["gho_token_ascii_0123456789", "tökén-ünïcode-🔐-value", ""],
    ids=["ascii", "unicode", "empty"],
)
def test_round_trip(key_a, plaintext):
    """C1: encrypt→decrypt returns the original plaintext for ascii/unicode/empty."""
    assert crypto.decrypt(crypto.encrypt(plaintext)) == plaintext


def test_blob_wire_shape(key_a):
    """C2: blob is 3 dot-joined valid-base64 parts; IV=12 bytes, tag=16 bytes."""
    blob = crypto.encrypt("some-secret-token")
    parts = blob.split(".")
    assert len(parts) == 3
    decoded = [base64.b64decode(p, validate=True) for p in parts]  # raises if not b64
    iv, tag, ciphertext = decoded
    assert len(iv) == 12
    assert len(tag) == 16
    assert len(ciphertext) > 0


def test_confidentiality_and_random_iv(key_a):
    """C3: ciphertext != plaintext bytes, and a fresh IV makes repeats differ."""
    plaintext = "gho_repeated_secret_value"
    blob1 = crypto.encrypt(plaintext)
    blob2 = crypto.encrypt(plaintext)
    assert blob1 != blob2  # random 12-byte IV per call

    iv1, _tag1, ct1 = (base64.b64decode(p, validate=True) for p in blob1.split("."))
    assert ct1 != plaintext.encode("utf-8")  # not stored in the clear
    iv2, _tag2, _ct2 = (base64.b64decode(p, validate=True) for p in blob2.split("."))
    assert iv1 != iv2


@pytest.mark.parametrize(
    "blob",
    ["only-two.parts", "a.b.c.d", "noseparatorsatall"],
    ids=["two-parts", "four-parts", "one-part"],
)
def test_malformed_wrong_part_count(key_a, blob):
    """C4: a blob without exactly 3 dot-joined parts is rejected."""
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(blob)


def test_malformed_bad_base64(key_a):
    """C5: a part that is not valid base64 is rejected."""
    # `!!!!` and spaces are not valid base64 payloads.
    with pytest.raises(TokenCryptoError):
        crypto.decrypt("!!!!.@@@@.####")


def test_malformed_bad_iv_length(key_a):
    """C6: a decoded IV of the wrong length is rejected (not passed to AESGCM)."""
    good = crypto.encrypt("x").split(".")
    short_iv = base64.b64encode(b"\x00\x01\x02").decode("ascii")  # 3 bytes, not 12
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(".".join([short_iv, good[1], good[2]]))


def test_malformed_bad_tag_length(key_a):
    """C6: a decoded tag of the wrong length is rejected."""
    good = crypto.encrypt("x").split(".")
    short_tag = base64.b64encode(b"\x00" * 4).decode("ascii")  # 4 bytes, not 16
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(".".join([good[0], short_tag, good[2]]))


def test_wrong_key_auth_tag_failure(monkeypatch):
    """C7: a blob encrypted under one key fails to decrypt under another."""
    _use_key(monkeypatch, KEY_A)
    blob = crypto.encrypt("gho_secret_under_key_a")
    _use_key(monkeypatch, KEY_B)
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(blob)


def test_tampered_ciphertext_auth_tag_failure(key_a):
    """C8: flipping a single ciphertext byte trips the GCM auth tag."""
    iv_b64, tag_b64, ct_b64 = crypto.encrypt("gho_pristine_token").split(".")
    ct = bytearray(base64.b64decode(ct_b64, validate=True))
    ct[0] ^= 0x01  # flip one bit of the first ciphertext byte
    tampered = ".".join([iv_b64, tag_b64, base64.b64encode(bytes(ct)).decode("ascii")])
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(tampered)


def test_missing_key_rejected(monkeypatch):
    """C9: with no encryption_key configured, encrypt and decrypt both raise."""
    _use_key(monkeypatch, None)
    with pytest.raises(TokenCryptoError):
        crypto.encrypt("anything")
    with pytest.raises(TokenCryptoError):
        crypto.decrypt(INTEROP_BLOB)


def test_interop_decrypts_ts_generated_blob(monkeypatch):
    """C10: a blob produced by the TS/node crypto.ts decrypts here unchanged."""
    _use_key(monkeypatch, INTEROP_KEY)
    assert crypto.decrypt(INTEROP_BLOB) == INTEROP_PLAINTEXT


def test_error_message_never_leaks_plaintext(key_a):
    """C11: TokenCryptoError text carries no plaintext (structural desc only)."""
    plaintext = "gho_super_secret_leak_probe_value"
    iv_b64, tag_b64, ct_b64 = crypto.encrypt(plaintext).split(".")
    ct = bytearray(base64.b64decode(ct_b64, validate=True))
    ct[0] ^= 0x01
    tampered = ".".join([iv_b64, tag_b64, base64.b64encode(bytes(ct)).decode("ascii")])
    try:
        crypto.decrypt(tampered)
    except TokenCryptoError as exc:
        assert plaintext not in str(exc)
    else:  # pragma: no cover - the tamper must fail
        pytest.fail("tampered blob unexpectedly decrypted")
