# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    StrictFloat,
    StrictInt,
    StrictStr,
)


class Model(RootModel[Any]):
    root: Any


class InTokens(RootModel[StrictInt]):
    root: StrictInt = Field(..., ge=0, le=9007199254740991)


class OutTokens(RootModel[StrictInt]):
    root: StrictInt = Field(..., ge=0, le=9007199254740991)


class CachedTokens(RootModel[StrictInt]):
    root: StrictInt = Field(..., ge=0, le=9007199254740991)


class CostUsd(RootModel[StrictFloat]):
    root: StrictFloat = Field(..., ge=0.0)


class Usage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    in_tokens: InTokens | None
    out_tokens: OutTokens | None
    cached_tokens: CachedTokens | None
    cost_usd: CostUsd | None


class PromptVersion(RootModel[StrictInt]):
    root: StrictInt = Field(..., gt=0, le=9007199254740991)


class Status(StrEnum):
    ok = 'ok'
    timeout = 'timeout'
    http_error = 'http_error'
    invalid_output = 'invalid_output'
    cancelled = 'cancelled'


class Usage1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    in_tokens: InTokens | None
    out_tokens: OutTokens | None
    cached_tokens: CachedTokens | None
    cost_usd: CostUsd | None


class AttemptRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: StrictStr = Field(..., min_length=1)
    run_id: StrictStr = Field(..., min_length=1)
    step: StrictInt = Field(..., ge=0, le=9007199254740991)
    attempt: StrictInt = Field(..., ge=0, le=9007199254740991)
    model: StrictStr | None
    prompt_version: PromptVersion | None
    prompt_hash: StrictStr | None
    messages: list[dict[StrictStr, Any]]
    tools: list[dict[StrictStr, Any]] | None
    output: Any
    status: Status
    error: StrictStr | None
    usage: Usage1
    provider_call_id: StrictStr | None
    latency_ms: StrictInt = Field(..., ge=0, le=9007199254740991)
    ts: StrictStr = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$',
    )


class Status1(StrEnum):
    running = 'running'
    ok = 'ok'
    end_of_rope = 'end_of_rope'
    invalid = 'invalid'
    budget = 'budget'
    loop_cap = 'loop_cap'


class TotalCostUsd(RootModel[StrictFloat]):
    root: StrictFloat = Field(..., ge=0.0)


class FinishedAt(RootModel[StrictStr]):
    root: StrictStr = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$',
    )


class RunRecord(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: StrictStr = Field(..., min_length=1)
    context_kind: StrictStr = Field(..., max_length=32, min_length=1)
    context_id: StrictStr = Field(..., max_length=64)
    role: StrictStr = Field(..., max_length=64, min_length=1)
    status: Status1
    steps: StrictInt = Field(..., ge=0, le=9007199254740991)
    total_cost_usd: TotalCostUsd | None
    created_at: StrictStr = Field(
        ...,
        pattern='^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d+)?(Z|[+-]\\d{2}:\\d{2})$',
    )
    finished_at: FinishedAt | None
