# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class AlertsSeenResponse(BaseModel):
    ok: Literal[True]
    updated: Annotated[int, Field(ge=0)]


class ApiError(BaseModel):
    error: str


class AppNotConfigured(BaseModel):
    error: str


class AuditEnqueuedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['audit_enqueued']
    queuePosition: Annotated[int, Field(ge=0)]


class BenchCoverage(BaseModel):
    describedEvents: Annotated[int, Field(ge=0)]
    renderedRows: Annotated[int, Field(ge=0)]
    anonymousRows: Annotated[int, Field(ge=0)]
    fidelityDefects: Annotated[int, Field(ge=0)]
    falseTargetEvents: Annotated[int, Field(ge=0)]
    falseTargetRows: Annotated[int, Field(ge=0)]
    predicateVersion: str


class BenchEmptyRate(BaseModel):
    k: Literal[0]
    n: Literal[0]
    point: None
    lower: None
    upper: None


class BenchLatency(BaseModel):
    p50: int | None
    p95: int | None
    p99: int | None


class BenchMeasuredRate(BaseModel):
    k: Annotated[int, Field(ge=0)]
    n: Annotated[int, Field(gt=0)]
    point: Annotated[float, Field(ge=0.0, le=1.0)]
    lower: Annotated[float, Field(ge=0.0, le=1.0)]
    upper: Annotated[float, Field(ge=0.0, le=1.0)]


class BenchObservedModel(BaseModel):
    role: str
    model: str


class BillingCheckoutResponse(BaseModel):
    url: str
    sessionId: str


class BillingInstallationRequest(BaseModel):
    installationId: Annotated[int, Field(gt=0)]


class BillingPortalResponse(BaseModel):
    url: str


class MaxSyscalls(RootModel[float]):
    root: Annotated[float, Field(gt=0.0)] = None


class MaxBytesCapture(RootModel[float]):
    root: Annotated[float, Field(gt=0.0)] = None


class Budget(BaseModel):
    wallMs: Annotated[float, Field(gt=0.0)]
    maxSyscalls: MaxSyscalls | None = None
    maxBytesCapture: MaxBytesCapture | None = None


class CryptoOp(BaseModel):
    method: str
    algo: str


class DealBreaker(BaseModel):
    check: str
    detail: str


class DependencyGroups(BaseModel):
    prod: dict[str, str] | None = {}
    dev: dict[str, str] | None = {}
    optional: dict[str, str] | None = {}
    peer: dict[str, str] | None = {}


class EntryPoints(BaseModel):
    install: list[str]
    runtime: list[str]
    bin: list[str]


class EvalCall(BaseModel):
    code: str


class EventSummary(BaseModel):
    uniqueHosts: list[str] | None = []
    uniqueSyscalls: list[str] | None = []
    filesWritten: list[str] | None = []
    dnsQueries: list[str] | None = []


class Derived(BaseModel):
    jsFrame: str | None = None
    module: str | None = None
    callStack: list[str] | None = []
    confidence: Annotated[
        Literal['high', 'low', 'none'] | None, Field(title='CorrelationConfidence')
    ] = 'none'


class EvidenceRef(BaseModel):
    kind: Annotated[Literal['run', 'static', 'diff'], Field(title='EvidenceRefKind')]
    id: str
    hash: str


class FilePatchRef(BaseModel):
    path: str
    patchHash: str


class FileRecord(BaseModel):
    path: str
    fileType: str
    sizeBytes: float
    permissions: str
    isBinary: bool
    binaryType: str | None = None


class FileSummary(BaseModel):
    file: str
    summary: str | None = ''
    capabilities: list[str] | None = []


class FileVerdict(BaseModel):
    file: str
    capabilities: list[str] | None = []
    suspiciousPatterns: list[str] | None = []
    suspiciousLines: str | None = None
    summary: str
    riskContribution: Annotated[int, Field(ge=0, le=10)]


class FocusRange(BaseModel):
    file: str
    range: str


class FsOperation(BaseModel):
    op: str
    path: str
    preview: str | None = ''


class HypothesisCounts(BaseModel):
    total: Annotated[int, Field(ge=0)]
    open: Annotated[int, Field(ge=0)]
    inProgress: Annotated[int, Field(ge=0)]
    confirmed: Annotated[int, Field(ge=0)]
    refuted: Annotated[int, Field(ge=0)]
    deferred: Annotated[int, Field(ge=0)]


class HypothesisResolution(BaseModel):
    reason: str
    by: str


class Installation(BaseModel):
    id: int
    accountLogin: str
    accountType: str
    suspended: bool


class LifecycleHook(
    RootModel[Literal['preinstall', 'install', 'postinstall', 'prepare']]
):
    root: Annotated[
        Literal['preinstall', 'install', 'postinstall', 'prepare'],
        Field(title='LifecycleHook'),
    ]


class NetworkCall(BaseModel):
    method: str
    url: str
    bodyPreview: str | None = ''


class ObserveFlags(BaseModel):
    kernel: bool
    network: bool
    fsDiff: bool
    node: bool
    inspector: bool | None = False


class OkResponse(BaseModel):
    ok: Literal[True]


class OrgsResponse(BaseModel):
    installations: list[Installation]
    installUrl: str


class PackageMetadata(BaseModel):
    name: str | None = None
    version: str | None = None
    description: str | None = None
    license: str | None = None
    homepage: str | None = None
    keywords: list[str] | None = []
    repository: str | dict[str, Any] | None = None


class PhaseLog(BaseModel):
    phase: str
    durationMs: float
    input: dict[str, Any] | None = {}
    output: dict[str, Any] | None = {}


class PlanLimits(BaseModel):
    protectedRepos: Annotated[int, Field(ge=0)]
    publicRepoAudits: Annotated[int, Field(ge=0)]
    monthlyAudits: Annotated[int, Field(ge=0)]


class PlantedFileRef(BaseModel):
    path: str
    contentHash: str


class ProcessSpawn(BaseModel):
    cmd: str
    args: list[str] | None = []


class PublicRepoScanRequest(BaseModel):
    repository: str
    installationId: int | None = None


class PublicRepo(BaseModel):
    githubRepoId: int
    owner: str
    name: str
    fullName: str
    htmlUrl: str
    defaultBranch: str
    lockfilePath: str
    lockfileSha: str


class ReauthRequired(BaseModel):
    error: str
    reauth: Literal[True]


class ResolvedPackage(BaseModel):
    path: str
    needsCleanup: bool | None = False
    tmpdir: str | None = None


class RunError(BaseModel):
    kind: Annotated[
        Literal['CrashError', 'TimeoutError', 'SensorError', 'SetupError'],
        Field(title='RunErrorKind'),
    ]
    detail: str


class ScanAlreadyRunning(BaseModel):
    error: str
    scanId: int


class ScanDoneFrame(BaseModel):
    type: Literal['done']


class ScanStartedResponse(BaseModel):
    scanId: int


class SessionUser(BaseModel):
    id: int
    login: str
    name: str | None
    email: str | None
    avatarUrl: str | None


class StubUrlRef(BaseModel):
    pattern: str
    responseHash: str | None


class SubscriptionPrice(BaseModel):
    amount: int | None
    currency: str | None
    interval: str | None


class TimerRecord(BaseModel):
    type: str
    ms: float
    source: str | None = ''


class ToolCall(BaseModel):
    tool: str
    args: dict[str, Any] | None = {}


class TriageHypothesis(BaseModel):
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    description: str


class Trigger(BaseModel):
    kind: Annotated[
        Literal['entrypoint', 'lifecycle', 'bin', 'subpath'], Field(title='TriggerKind')
    ]
    target: str
    argv: list[str] | None = []
    stdin: str | None = None


class UsageBucket(BaseModel):
    used: Annotated[int, Field(ge=0)]
    limit: Annotated[int, Field(ge=0)]
    remaining: int | None


class ValidationIssue(BaseModel):
    field: str
    message: str


class AccountEntitlements(BaseModel):
    installationId: int
    accountLogin: str
    plan: Annotated[Literal['free', 'pro'], Field(title='AccountPlan')]
    subscriptionStatus: str
    protectedRepos: UsageBucket
    publicRepoAudits: UsageBucket
    monthlyAudits: UsageBucket


class Alert(BaseModel):
    id: int
    org: str
    repoId: int | None
    packageName: str
    version: str
    outcome: Literal['DANGEROUS']
    origin: Annotated[
        Literal['repo_scan', 'public_repo_scan', 'dep_tree', 'bench_run', 'watchlist'],
        Field(title='AuditSetOrigin'),
    ]
    message: str
    seen: bool
    createdAt: str


class AlertsResponse(BaseModel):
    alerts: list[Alert]


class AuditErrorEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['audit_error']
    error: str
    code: str
    retryable: bool


class AuditSetItem(BaseModel):
    name: str
    version: str
    direct: bool
    range: str | None
    outcome: Literal['SAFE', 'ERROR', 'DANGEROUS'] | None
    verdictReason: str | None
    evidenceCount: Annotated[int, Field(ge=0)]
    auditedAt: str | None
    jobState: Literal['queued', 'running', 'failed'] | None
    cached: bool


class AuditSetRollup(BaseModel):
    outcome: Literal['SAFE', 'ERROR', 'DANGEROUS'] | None
    total: Annotated[int, Field(ge=0)]
    safe: Annotated[int, Field(ge=0)]
    dangerous: Annotated[int, Field(ge=0)]
    error: Annotated[int, Field(ge=0)]
    pending: Annotated[int, Field(ge=0)]
    cached: Annotated[int, Field(ge=0)]


class AuditSet(BaseModel):
    id: int
    origin: Annotated[
        Literal['repo_scan', 'public_repo_scan', 'dep_tree', 'bench_run', 'watchlist'],
        Field(title='AuditSetOrigin'),
    ]
    trigger: Annotated[
        Literal['manual', 'push', 'reconcile', 'publish'],
        Field(title='AuditSetTrigger'),
    ]
    status: Annotated[Literal['running', 'done'], Field(title='AuditSetStatus')]
    rollup: AuditSetRollup
    commitSha: str | None
    startedAt: str
    finishedAt: str | None


class AuditStartedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['audit_started']
    packageName: str


class BaseAuditEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]


class BenchCorpus(BaseModel):
    id: int
    name: str
    version: str
    datasetVersion: str
    source: Annotated[
        Literal['datadog', 'negative-control', 'watchlist'],
        Field(title='BenchCorpusSource'),
    ]
    manifestSha: str
    generatedAt: str
    entryCount: Annotated[int, Field(ge=0)]


class BenchDetectionBand(BaseModel):
    reliable: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]
    optimistic: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]


class BenchEntry(BaseModel):
    id: int
    corpusId: int
    fixtureName: str
    packageName: str
    version: str
    category: str
    expectedVerdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    discoveryDate: str | None
    rationale: str | None
    sourceId: str | None


class BenchLedgerRow(BaseModel):
    fixtureName: str
    packageName: str
    version: str
    category: str
    discoveryDate: str | None
    expectedVerdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    outcomes: list[
        Literal[
            'CAUGHT_PROVED',
            'CAUGHT_STRUCTURAL',
            'MISSED',
            'CLEARED',
            'FALSE_ALARM_PROVED',
            'FALSE_ALARM_STRUCTURAL',
            'ABSTAINED',
            'VOID',
        ]
    ]
    bucket: Annotated[
        Literal[
            'UNOBSERVED',
            'CAUGHT_ALWAYS',
            'CAUGHT_SOMETIMES',
            'MISSED_ALWAYS',
            'ABSTAINED_ALWAYS',
            'NEVER_CAUGHT_MIXED',
            'CLEARED_ALWAYS',
            'CLEARED_SOMETIMES',
            'FALSE_ALARM_ALWAYS',
            'MIXED',
        ],
        Field(title='BenchEntryBucket'),
    ]
    auditIds: list[str | None]


class BenchRunItem(BaseModel):
    runId: int
    entryId: int
    runIndex: Annotated[int, Field(ge=0)]
    auditId: str | None
    verdict: Literal['SAFE', 'DANGEROUS'] | None
    durationMs: int | None
    error: str | None
    confirmedCount: Annotated[int, Field(ge=0)]
    dealbreaker: str | None
    tokensPrompt: int | None
    tokensCompletion: int | None


class BenchRunMetrics(BaseModel):
    runId: int
    engineSha: str
    datasetVersion: str
    manifestSha: str
    observedModels: list[BenchObservedModel]
    runsPerEntry: Annotated[int, Field(ge=0)]
    stabilityMeasured: bool
    publishable: bool
    detection: BenchDetectionBand
    missRate: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]
    abstentionRate: Annotated[
        BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')
    ]
    neverCaughtMixed: Annotated[int, Field(ge=0)]
    specificity: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]
    falseAlarmRate: Annotated[
        BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')
    ]
    proofShare: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]
    dealbreakerShare: Annotated[
        BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')
    ]
    attempted: Annotated[int, Field(ge=0)]
    voidCount: Annotated[int, Field(ge=0)]
    voidShare: float | None
    voidCauses: dict[str, int]
    unobservedEntries: Annotated[int, Field(ge=0)]
    unanimity: Annotated[BenchMeasuredRate | BenchEmptyRate, Field(title='BenchRate')]
    flips: list[str]
    latencyMs: BenchLatency
    tokensPrompt: int | None
    tokensCompletion: int | None
    tokenCostUsd: float | None
    coverage: BenchCoverage | None
    coveragePredicate: str
    ledger: list[BenchLedgerRow]


class BenchRunRow(BaseModel):
    entry: BenchEntry
    items: list[BenchRunItem]


class BenchRunRowsResponse(BaseModel):
    runId: int
    rows: list[BenchRunRow]


class BenchRun(BaseModel):
    id: int
    corpusId: int
    engineSha: str
    observedModels: list[BenchObservedModel]
    modelId: str | None
    sandboxImageDigest: str
    runsPerEntry: Annotated[int, Field(gt=0)]
    set: AuditSet
    tokenCostUsd: float | None


class BenchRunsResponse(BaseModel):
    runs: list[BenchRun]


class CapExceeded(BaseModel):
    error: str
    cap: Literal[True]
    resource: Annotated[
        Literal['protected_repos', 'public_repo_audits', 'monthly_audits'],
        Field(title='CapResource'),
    ]
    installationId: int
    entitlements: AccountEntitlements


class Claim(BaseModel):
    kind: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    gating: (
        Literal['time_gate', 'geo_gate', 'ci_gate', 'inspector_gate', 'docker_gate']
        | None
    ) = None


class DependenciesProvisionedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['dependencies_provisioned']
    installed: bool
    packageCount: Annotated[int, Field(ge=0)]
    skipped: str | None = None
    error: str | None = None


class EvidenceEvent(BaseModel):
    stream: Annotated[
        Literal[
            'L1:seccomp',
            'L2:pcap',
            'L3:fsDiff',
            'L4:monkey',
            'L4:v8inspector',
            'engine',
        ],
        Field(title='StreamKind'),
    ]
    timestamp: Annotated[float, Field(ge=0.0)]
    pid: int
    kind: Annotated[
        Literal[
            'openat',
            'read',
            'write',
            'connect',
            'sendto',
            'execve',
            'clone',
            'unlink',
            'rename',
            'link',
            'dns_query',
            'http_request',
            'tls_sni',
            'tcp_syn',
            'file_created',
            'file_modified',
            'file_deleted',
            'require',
            'env_access',
            'fs_op',
            'network',
            'process',
            'eval',
            'crypto',
            'timer',
            'script_parsed',
            'debugger_paused',
            'truncated',
            'setup_bypass',
            'error',
        ],
        Field(title='EventKind'),
    ]
    raw: Any | None = None
    normalized: dict[str, Any] | None = None
    derived: Derived | None = None


class FileAnalyzingEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_analyzing']
    file: str


class FileListEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_list']
    files: list[FileRecord]


class FileVerdictEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_verdict']
    verdict: FileVerdict


class GraphBuiltEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['graph_built']
    nodeCount: Annotated[int, Field(ge=0)]
    addedCount: Annotated[int, Field(ge=0)]
    mergedCount: Annotated[int, Field(ge=0)]


class HypothesisEmittedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['hypothesis_emitted']
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    file: str


class HypothesisResolvedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['hypothesis_resolved']
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    state: Annotated[
        Literal['OPEN', 'IN_PROGRESS', 'CONFIRMED', 'REFUTED', 'DEFERRED'],
        Field(title='HypothesisState'),
    ]
    by: str
    reason: str


class Hypothesis(BaseModel):
    hypId: str
    description: str
    claim: Claim
    focusFiles: list[str] | None = []
    focusLines: Annotated[list[FocusRange] | None, Field(validate_default=True)] = []
    experiment: Annotated[list[ToolCall] | None, Field(validate_default=True)] = []
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'] | None,
        Field(title='HypothesisSeverity'),
    ] = 'medium'
    parentHypId: str | None = None
    childHypIds: list[str] | None = []
    state: Annotated[
        Literal['OPEN', 'IN_PROGRESS', 'CONFIRMED', 'REFUTED', 'DEFERRED'],
        Field(title='HypothesisState'),
    ]
    createdBy: str
    evidenceRefs: Annotated[list[EvidenceRef] | None, Field(validate_default=True)] = []
    createdAt: str
    resolvedAt: str | None = None
    resolution: HypothesisResolution | None = None


class InstrumentationLog(BaseModel):
    modulesLoaded: list[str] | None = []
    networkCalls: Annotated[list[NetworkCall] | None, Field(validate_default=True)] = []
    fsOperations: Annotated[list[FsOperation] | None, Field(validate_default=True)] = []
    envAccess: list[str] | None = []
    processSpawns: Annotated[
        list[ProcessSpawn] | None, Field(validate_default=True)
    ] = []
    evalCalls: Annotated[list[EvalCall] | None, Field(validate_default=True)] = []
    cryptoOps: Annotated[list[CryptoOp] | None, Field(validate_default=True)] = []
    timers: Annotated[list[TimerRecord] | None, Field(validate_default=True)] = []


class IntentExtractedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['intent_extracted']
    statedPurpose: str
    expectedCapabilities: list[str] | None = []


class InventoryFlag(BaseModel):
    severity: Annotated[Literal['info', 'warn', 'critical'], Field(title='Severity')]
    check: str
    detail: str
    file: str | None = None


class InventoryMetaEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['inventory_meta']
    scripts: dict[str, str]
    dependencies: DependencyGroups
    entryPoints: EntryPoints
    metadata: PackageMetadata


class InventoryReport(BaseModel):
    metadata: PackageMetadata
    scripts: dict[str, str]
    entryPoints: EntryPoints
    dependencies: dict[str, dict[str, str]]
    files: list[FileRecord]
    flags: list[InventoryFlag]
    dealbreaker: DealBreaker | None = None


class PanelRepo(BaseModel):
    id: int
    installationId: int
    owner: str
    name: str
    fullName: str
    private: bool
    defaultBranch: str
    protected: bool
    lastScan: AuditSet | None


class PhaseCompletedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['phase_completed']
    phase: str
    durationMs: float


class PhaseStartedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['phase_started']
    phase: str


class PlanCatalog(BaseModel):
    free: PlanLimits
    pro: PlanLimits


class PublicRepoScan(BaseModel):
    id: int
    repo: PublicRepo
    set: AuditSet
    requestedBy: int
    installationId: int | None
    accountLogin: str | None


class PublicRepoScansResponse(BaseModel):
    scans: list[PublicRepoScan]


class ReplayEntry(BaseModel):
    auditId: str
    packageName: str
    version: str | None
    verdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    durationMs: Annotated[int, Field(ge=0)]
    recordedAt: str


class ReplayGalleryResponse(BaseModel):
    replays: list[ReplayEntry]


class RepoDetailResponse(BaseModel):
    repo: PanelRepo
    set: AuditSet | None
    depsTruncated: bool
    deps: list[AuditSetItem]
    alerts: list[Alert]


class ReposResponse(BaseModel):
    repos: list[PanelRepo]


class ScanDepFrame(BaseModel):
    type: Literal['dep']
    item: AuditSetItem


class ScanProgressFrame(BaseModel):
    type: Literal['progress']
    status: Annotated[Literal['running', 'done'], Field(title='AuditSetStatus')]
    rollup: AuditSetRollup


class ScanStreamFrame(RootModel[ScanDepFrame | ScanProgressFrame | ScanDoneFrame]):
    root: Annotated[
        ScanDepFrame | ScanProgressFrame | ScanDoneFrame, Field(title='ScanStreamFrame')
    ]


class SessionResponse(BaseModel):
    user: SessionUser


class SetupApplied(BaseModel):
    env: dict[str, str] | None = {}
    date: str | None = None
    plantFiles: Annotated[list[PlantedFileRef] | None, Field(validate_default=True)] = (
        []
    )
    stubUrls: Annotated[list[StubUrlRef] | None, Field(validate_default=True)] = []
    hostname: str | None = None
    locale: str | None = None
    patches: Annotated[list[FilePatchRef] | None, Field(validate_default=True)] = []
    preloadHash: str | None = None


class TriageCompleteEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['triage_complete']
    hypothesisCount: Annotated[int, Field(ge=0)]
    hypotheses: list[TriageHypothesis]


class TriageProgressEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['triage_progress']
    current: Annotated[int, Field(ge=0)]
    total: Annotated[int, Field(ge=0)]
    file: str


class ValidationFailed(BaseModel):
    error: str
    details: list[ValidationIssue]


class VerdictReachedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['verdict_reached']
    verdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    rationale: str
    counts: HypothesisCounts
    confirmedCount: Annotated[int, Field(ge=0)]


class AuditEvent(
    RootModel[
        AuditStartedEvent
        | AuditEnqueuedEvent
        | PhaseStartedEvent
        | PhaseCompletedEvent
        | DependenciesProvisionedEvent
        | FileListEvent
        | InventoryMetaEvent
        | IntentExtractedEvent
        | FileAnalyzingEvent
        | TriageProgressEvent
        | HypothesisEmittedEvent
        | FileVerdictEvent
        | TriageCompleteEvent
        | GraphBuiltEvent
        | HypothesisResolvedEvent
        | VerdictReachedEvent
        | AuditErrorEvent
    ]
):
    root: Annotated[
        AuditStartedEvent
        | AuditEnqueuedEvent
        | PhaseStartedEvent
        | PhaseCompletedEvent
        | DependenciesProvisionedEvent
        | FileListEvent
        | InventoryMetaEvent
        | IntentExtractedEvent
        | FileAnalyzingEvent
        | TriageProgressEvent
        | HypothesisEmittedEvent
        | FileVerdictEvent
        | TriageCompleteEvent
        | GraphBuiltEvent
        | HypothesisResolvedEvent
        | VerdictReachedEvent
        | AuditErrorEvent,
        Field(title='AuditEvent'),
    ]


class AuditReport(BaseModel):
    schemaVersion: Literal[2] = 2
    verdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    rationale: str | None = ''
    counts: HypothesisCounts
    confirmedHypIds: list[str] | None = []
    hypotheses: Annotated[list[Hypothesis] | None, Field(validate_default=True)] = []
    fileSummaries: Annotated[list[FileSummary] | None, Field(validate_default=True)] = (
        []
    )
    dealbreaker: DealBreaker | None = None
    trace: Annotated[list[PhaseLog] | None, Field(validate_default=True)] = []


class BenchCorporaResponse(BaseModel):
    corpora: list[BenchCorpus]


class BenchRunDetailResponse(BaseModel):
    corpus: BenchCorpus
    run: BenchRun
    rows: list[BenchRunRow]


class BillingResponse(BaseModel):
    accounts: list[AccountEntitlements]
    plans: PlanCatalog
    checkoutEnabled: bool
    price: SubscriptionPrice | None


class HypothesisGraphSnapshot(BaseModel):
    version: Literal[1]
    auditId: str
    nodes: list[Hypothesis]
    createdAt: str
    updatedAt: str


class PublicRepoScanDetailResponse(BaseModel):
    scan: PublicRepoScan
    depsTruncated: bool
    deps: list[AuditSetItem]


class RunArtifact(BaseModel):
    runId: str
    triggerUsed: Trigger
    setupApplied: SetupApplied
    observe: ObserveFlags
    budget: Budget
    wallMs: Annotated[float, Field(ge=0.0)]
    exitCode: int | None
    timedOut: bool
    events: list[EvidenceEvent]
    stdoutHash: str | None = None
    stderrHash: str | None = None
    fsDiffHash: str | None = None
    pcapHash: str | None = None
    straceLogHash: str | None = None
    inspectorLogHash: str | None = None
    eventSummary: EventSummary
    error: RunError | None = None
    contentHash: str
    createdAt: str
