# generated by datamodel-codegen:
#   filename:  contract.schema.json

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, RootModel


class Model(RootModel[Any]):
    root: Any


class AgentReasoningEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['agent_reasoning']
    text: str
    step: int


class AttackPathway(
    RootModel[
        Literal[
            'DEP_INJECT_ENCRYPTED',
            'LIFECYCLE_BINARY_DROP',
            'MAINTAINER_SABOTAGE',
            'GEO_GATED_WIPER',
            'WORM_PROPAGATION',
            'ACCOUNT_TAKEOVER_CRYPTO',
            'CDN_DOM_DRAINER',
            'MULTI_STAGE_DNS',
            'TELEMETRY_RAT',
            'BUILD_PLUGIN_EXFIL',
        ]
    ]
):
    root: Annotated[
        Literal[
            'DEP_INJECT_ENCRYPTED',
            'LIFECYCLE_BINARY_DROP',
            'MAINTAINER_SABOTAGE',
            'GEO_GATED_WIPER',
            'WORM_PROPAGATION',
            'ACCOUNT_TAKEOVER_CRYPTO',
            'CDN_DOM_DRAINER',
            'MULTI_STAGE_DNS',
            'TELEMETRY_RAT',
            'BUILD_PLUGIN_EXFIL',
        ],
        Field(title='AttackPathway'),
    ]


class MaxSyscalls(RootModel[float]):
    root: Annotated[float, Field(gt=0.0)] = None


class MaxBytesCapture(RootModel[float]):
    root: Annotated[float, Field(gt=0.0)] = None


class Budget(BaseModel):
    wallMs: Annotated[float, Field(gt=0.0)]
    maxSyscalls: MaxSyscalls | None = None
    maxBytesCapture: MaxBytesCapture | None = None


class CryptoOp(BaseModel):
    method: str
    algo: str


class DealBreaker(BaseModel):
    check: str
    detail: str


class EntryPoints(BaseModel):
    install: list[str]
    runtime: list[str]
    bin: list[str]


class EvalCall(BaseModel):
    code: str


class EventSummary(BaseModel):
    uniqueHosts: list[str] | None = []
    uniqueSyscalls: list[str] | None = []
    filesWritten: list[str] | None = []
    dnsQueries: list[str] | None = []


class Derived(BaseModel):
    jsFrame: str | None = None
    module: str | None = None
    callStack: list[str] | None = []
    confidence: Annotated[
        Literal['high', 'low', 'none'] | None, Field(title='CorrelationConfidence')
    ] = 'none'


class EvidenceRef(BaseModel):
    kind: Annotated[Literal['run', 'static', 'diff'], Field(title='EvidenceRefKind')]
    id: str
    hash: str


class FilePatchRef(BaseModel):
    path: str
    patchHash: str


class FileRecord(BaseModel):
    path: str
    fileType: str
    sizeBytes: float
    permissions: str
    isBinary: bool
    binaryType: str | None = None


class FileSummary(BaseModel):
    file: str
    summary: str | None = ''
    capabilities: list[str] | None = []


class FileVerdict(BaseModel):
    file: str
    capabilities: list[str] | None = []
    suspiciousPatterns: list[str] | None = []
    suspiciousLines: str | None = None
    summary: str
    riskContribution: Annotated[int, Field(ge=0, le=10)]


class Finding(BaseModel):
    capability: Annotated[
        str | None, Field(description="CapabilityEnum value, e.g. 'NETWORK'")
    ] = 'UNKNOWN'
    confidence: Annotated[
        Literal['SUSPECTED', 'LIKELY', 'CONFIRMED'] | None, Field(title='Confidence')
    ] = 'SUSPECTED'
    fileLine: Annotated[str | None, Field(description="e.g. 'lib/index.js:42-67'")] = ''
    problem: Annotated[
        str | None, Field(description='Human-readable description of the threat')
    ] = ''
    evidence: Annotated[
        str | None, Field(description='Concrete data or observation')
    ] = ''
    reproductionStrategy: Annotated[
        str | None, Field(description='How to prove this in a reproducible test')
    ] = ''


class FocusArea(BaseModel):
    file: str
    lines: str | None = None
    reason: str


class FocusRange(BaseModel):
    file: str
    range: str


class FsOperation(BaseModel):
    op: str
    path: str
    preview: str | None = ''


class HypothesisCounts(BaseModel):
    total: Annotated[int, Field(ge=0)]
    open: Annotated[int, Field(ge=0)]
    inProgress: Annotated[int, Field(ge=0)]
    confirmed: Annotated[int, Field(ge=0)]
    refuted: Annotated[int, Field(ge=0)]
    deferred: Annotated[int, Field(ge=0)]


class HypothesisResolution(BaseModel):
    reason: str
    by: str


class Metadata(BaseModel):
    name: str | None
    version: str | None
    description: str | None
    license: str | None


class LifecycleHook(
    RootModel[Literal['preinstall', 'install', 'postinstall', 'prepare']]
):
    root: Annotated[
        Literal['preinstall', 'install', 'postinstall', 'prepare'],
        Field(title='LifecycleHook'),
    ]


class NetworkCall(BaseModel):
    method: str
    url: str
    bodyPreview: str | None = ''


class ObserveFlags(BaseModel):
    kernel: bool
    network: bool
    fsDiff: bool
    node: bool
    inspector: bool | None = False


class PackageMetadata(BaseModel):
    name: str | None = None
    version: str | None = None
    description: str | None = None
    license: str | None = None
    homepage: str | None = None
    keywords: list[str] | None = []
    repository: Any | None = None


class PhaseLog(BaseModel):
    phase: str
    durationMs: float
    input: dict[str, Any] | None = {}
    output: dict[str, Any] | None = {}


class PlantedFileRef(BaseModel):
    path: str
    contentHash: str


class ProcessSpawn(BaseModel):
    cmd: str
    args: list[str] | None = []


class Proof(BaseModel):
    capability: (
        Literal[
            'NETWORK',
            'DATA_EXFILTRATION',
            'DNS_EXFIL',
            'DOM_INJECT',
            'FILESYSTEM',
            'BINARY_DOWNLOAD',
            'PROCESS_SPAWN',
            'ENV_VARS',
            'CREDENTIAL_THEFT',
            'EVAL',
            'OBFUSCATION',
            'ENCRYPTED_PAYLOAD',
            'DOS_LOOP',
            'ANTI_AI_PROMPT',
            'GEO_GATING',
            'LIFECYCLE_HOOK',
            'WORM_PROPAGATION',
            'CLIPBOARD_HIJACK',
            'TELEMETRY_RAT',
            'BUILD_PLUGIN_EXFIL',
            'NPM_TOKEN_ABUSE',
        ]
        | None
    ) = None
    attackPathway: str | None = ''
    confidence: Annotated[
        Literal['SUSPECTED', 'LIKELY', 'CONFIRMED'] | None, Field(title='Confidence')
    ] = 'SUSPECTED'
    fileLine: str
    problem: str
    evidence: str
    kind: Annotated[
        Literal[
            'STRUCTURAL',
            'AI_STATIC',
            'AI_DYNAMIC',
            'TEST_CONFIRMED',
            'TEST_UNCONFIRMED',
        ]
        | None,
        Field(title='ProofKind'),
    ] = 'STRUCTURAL'
    contentHash: str | None = None
    reproducible: bool | None = False
    reproductionCmd: str | None = None
    testFile: str | None = None
    testHash: str | None = None
    testCode: str | None = None
    verifyError: str | None = None
    reasoningHash: str | None = None
    teeAttestationId: str | None = None


class ResolvedPackage(BaseModel):
    path: str
    needsCleanup: bool | None = False
    tmpdir: str | None = None


class RunError(BaseModel):
    kind: Annotated[
        Literal['CrashError', 'TimeoutError', 'SensorError', 'SetupError'],
        Field(title='RunErrorKind'),
    ]
    detail: str


class StubUrlRef(BaseModel):
    pattern: str
    responseHash: str


class TimerRecord(BaseModel):
    type: str
    ms: float
    source: str | None = ''


class ToolCall(BaseModel):
    tool: str
    args: dict[str, Any] | None = {}


class Hypothes(BaseModel):
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    description: str


class TriageResult(BaseModel):
    riskScore: Annotated[int, Field(ge=0, le=10)]
    riskSummary: str
    focusAreas: Annotated[list[FocusArea] | None, Field(validate_default=True)] = []


class Trigger(BaseModel):
    kind: Annotated[
        Literal['entrypoint', 'lifecycle', 'bin', 'subpath'], Field(title='TriggerKind')
    ]
    target: str
    argv: list[str] | None = []
    stdin: str | None = None


class AgentThinkingEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['agent_thinking']
    step: int


class AgentToolCallEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['agent_tool_call']
    tool: str
    args: dict[str, Any]
    step: int


class AgentToolResultEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['agent_tool_result']
    tool: str
    resultPreview: str
    step: int
    injectionDetected: bool


class AuditErrorEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['audit_error']
    error: str | None = None
    code: str | None = None
    retryable: bool | None = None


class AuditStartedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['audit_started']
    packageName: str


class BaseAuditEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]


class Claim(BaseModel):
    kind: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    gating: (
        Literal['time_gate', 'geo_gate', 'ci_gate', 'inspector_gate', 'docker_gate']
        | None
    ) = None


class EvidenceEvent(BaseModel):
    stream: Annotated[
        Literal[
            'L1:seccomp',
            'L2:pcap',
            'L3:fsDiff',
            'L4:monkey',
            'L4:v8inspector',
            'engine',
        ],
        Field(title='StreamKind'),
    ]
    timestamp: Annotated[float, Field(ge=0.0)]
    pid: int
    kind: Annotated[
        Literal[
            'openat',
            'read',
            'write',
            'connect',
            'sendto',
            'execve',
            'clone',
            'unlink',
            'rename',
            'link',
            'dns_query',
            'http_request',
            'tls_sni',
            'tcp_syn',
            'file_created',
            'file_modified',
            'file_deleted',
            'require',
            'env_access',
            'fs_op',
            'network',
            'process',
            'eval',
            'crypto',
            'timer',
            'script_parsed',
            'debugger_paused',
            'truncated',
            'setup_bypass',
            'error',
        ],
        Field(title='EventKind'),
    ]
    raw: Any | None = None
    normalized: dict[str, Any] | None = None
    derived: Derived | None = None


class FileAnalyzingEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_analyzing']
    file: str


class FileListEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_list']
    files: list[FileRecord]


class FileVerdictEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['file_verdict']
    verdict: FileVerdict


class FindingDiscoveredEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['finding_discovered']
    finding: Finding


class HypothesisEmittedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['hypothesis_emitted']
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    file: str


class HypothesisResolvedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['hypothesis_resolved']
    hypId: str
    claim: Annotated[
        Literal[
            'env_exfil',
            'cred_theft',
            'binary_drop',
            'obfuscation',
            'persistence',
            'destructive',
            'propagation',
            'dos_loop',
            'clipboard_hijack',
            'dom_inject',
            'telemetry',
            'dns_exfil',
            'build_plugin_exfil',
        ],
        Field(title='ClaimKind'),
    ]
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'], Field(title='HypothesisSeverity')
    ]
    state: Annotated[
        Literal['OPEN', 'IN_PROGRESS', 'CONFIRMED', 'REFUTED', 'DEFERRED'],
        Field(title='HypothesisState'),
    ]
    by: str
    reason: str


class Hypothesis(BaseModel):
    hypId: str
    description: str
    claim: Claim
    focusFiles: list[str] | None = []
    focusLines: Annotated[list[FocusRange] | None, Field(validate_default=True)] = []
    experiment: Annotated[list[ToolCall] | None, Field(validate_default=True)] = []
    severity: Annotated[
        Literal['low', 'medium', 'high', 'critical'] | None,
        Field(title='HypothesisSeverity'),
    ] = 'medium'
    parentHypId: str | None = None
    childHypIds: list[str] | None = []
    state: Annotated[
        Literal['OPEN', 'IN_PROGRESS', 'CONFIRMED', 'REFUTED', 'DEFERRED'],
        Field(title='HypothesisState'),
    ]
    createdBy: str
    evidenceRefs: Annotated[list[EvidenceRef] | None, Field(validate_default=True)] = []
    createdAt: str
    resolvedAt: str | None = None
    resolution: HypothesisResolution | None = None


class InstrumentationLog(BaseModel):
    modulesLoaded: list[str] | None = []
    networkCalls: Annotated[list[NetworkCall] | None, Field(validate_default=True)] = []
    fsOperations: Annotated[list[FsOperation] | None, Field(validate_default=True)] = []
    envAccess: list[str] | None = []
    processSpawns: Annotated[
        list[ProcessSpawn] | None, Field(validate_default=True)
    ] = []
    evalCalls: Annotated[list[EvalCall] | None, Field(validate_default=True)] = []
    cryptoOps: Annotated[list[CryptoOp] | None, Field(validate_default=True)] = []
    timers: Annotated[list[TimerRecord] | None, Field(validate_default=True)] = []


class InventoryFlag(BaseModel):
    severity: Annotated[Literal['info', 'warn', 'critical'], Field(title='Severity')]
    check: str
    detail: str
    file: str | None = None


class InventoryMetaEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['inventory_meta']
    scripts: dict[str, str]
    dependencies: dict[str, dict[str, str]]
    entryPoints: EntryPoints
    metadata: Metadata


class InventoryReport(BaseModel):
    metadata: PackageMetadata
    scripts: dict[str, str]
    entryPoints: EntryPoints
    dependencies: dict[str, dict[str, str]]
    files: list[FileRecord]
    flags: list[InventoryFlag]
    dealbreaker: DealBreaker | None = None


class PhaseCompletedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['phase_completed']
    phase: str
    durationMs: float


class PhaseStartedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['phase_started']
    phase: str


class SetupApplied(BaseModel):
    env: dict[str, str] | None = {}
    date: str | None = None
    plantFiles: Annotated[list[PlantedFileRef] | None, Field(validate_default=True)] = (
        []
    )
    stubUrls: Annotated[list[StubUrlRef] | None, Field(validate_default=True)] = []
    hostname: str | None = None
    locale: str | None = None
    patches: Annotated[list[FilePatchRef] | None, Field(validate_default=True)] = []
    preloadHash: str | None = None


class TriageCompleteEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['triage_complete']
    hypothesisCount: Annotated[int, Field(ge=0)]
    hypotheses: list[Hypothes]


class TriageProgressEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['triage_progress']
    current: Annotated[int, Field(ge=0)]
    total: Annotated[int, Field(ge=0)]
    file: str


class VerdictReachedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['verdict_reached']
    verdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    rationale: str
    counts: HypothesisCounts
    confirmedCount: Annotated[int, Field(ge=0)]


class VerifyStartedEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['verify_started']
    totalTests: Annotated[int, Field(ge=0)]


class VerifyTestResultEvent(BaseModel):
    auditId: str
    timestamp: str
    seq: Annotated[int, Field(ge=0)]
    type: Literal['verify_test_result']
    proofIndex: Annotated[int, Field(ge=0)]
    testFile: str
    status: Literal['confirmed', 'unconfirmed', 'infra_error']
    error: str | None = None


class AuditEvent(
    RootModel[
        AuditStartedEvent
        | PhaseStartedEvent
        | PhaseCompletedEvent
        | FileListEvent
        | FileAnalyzingEvent
        | FileVerdictEvent
        | TriageCompleteEvent
        | TriageProgressEvent
        | AgentToolCallEvent
        | AgentToolResultEvent
        | AgentReasoningEvent
        | AgentThinkingEvent
        | FindingDiscoveredEvent
        | HypothesisEmittedEvent
        | HypothesisResolvedEvent
        | VerdictReachedEvent
        | InventoryMetaEvent
        | VerifyStartedEvent
        | VerifyTestResultEvent
        | AuditErrorEvent
    ]
):
    root: Annotated[
        AuditStartedEvent
        | PhaseStartedEvent
        | PhaseCompletedEvent
        | FileListEvent
        | FileAnalyzingEvent
        | FileVerdictEvent
        | TriageCompleteEvent
        | TriageProgressEvent
        | AgentToolCallEvent
        | AgentToolResultEvent
        | AgentReasoningEvent
        | AgentThinkingEvent
        | FindingDiscoveredEvent
        | HypothesisEmittedEvent
        | HypothesisResolvedEvent
        | VerdictReachedEvent
        | InventoryMetaEvent
        | VerifyStartedEvent
        | VerifyTestResultEvent
        | AuditErrorEvent,
        Field(title='AuditEvent'),
    ]


class AuditReport(BaseModel):
    schemaVersion: Literal[2] = 2
    verdict: Annotated[Literal['SAFE', 'DANGEROUS'], Field(title='Verdict')]
    rationale: str | None = ''
    counts: HypothesisCounts
    confirmedHypIds: list[str] | None = []
    hypotheses: Annotated[list[Hypothesis] | None, Field(validate_default=True)] = []
    fileSummaries: Annotated[list[FileSummary] | None, Field(validate_default=True)] = (
        []
    )
    dealbreaker: DealBreaker | None = None
    trace: Annotated[list[PhaseLog] | None, Field(validate_default=True)] = []


class HypothesisGraphSnapshot(BaseModel):
    version: Literal[1]
    auditId: str
    nodes: list[Hypothesis]
    createdAt: str
    updatedAt: str


class RunArtifact(BaseModel):
    runId: str
    triggerUsed: Trigger
    setupApplied: SetupApplied
    observe: ObserveFlags
    budget: Budget
    wallMs: Annotated[float, Field(ge=0.0)]
    exitCode: int | None
    timedOut: bool
    events: list[EvidenceEvent]
    stdoutHash: str | None = None
    stderrHash: str | None = None
    fsDiffHash: str | None = None
    pcapHash: str | None = None
    straceLogHash: str | None = None
    inspectorLogHash: str | None = None
    eventSummary: EventSummary
    error: RunError | None = None
    contentHash: str
    createdAt: str
