"""The bench harness building blocks. What every LLM app rebuilds — lever
expansion, repeats, concurrency, per-root and per-score persistence,
resume, summary, diff — factored behind two app-provided callables
(run_cell, score). The
domain (scenarios, fixtures, judges, ground truth, metrics) stays in the
app; only the machinery lives here.

An LLM system is nondeterministic, so "does it work" is unanswerable —
replaced by "how often, how well, at what cost, over a fixed input
population". A bench run varies levers one at a time and measures; cells
run through llm.run, so cost lands in the same ledger with
context_kind='bench'."""

from kit_llm.bench.expand import Cell, expand
from kit_llm.bench.evidence import (
    AmbiguousEvidenceAttempt,
    AttemptObservation,
    CampaignProtocol,
    EVIDENCE_BUNDLE_FORMAT,
    EVIDENCE_BYTES_FORMAT,
    EVIDENCE_FORMAT_VERSION,
    EVIDENCE_RECORD_FORMAT,
    EvidenceArtifactError,
    EvidenceBundleLocked,
    EvidenceIncomplete,
    EvidenceIssue,
    EvidenceLockUnavailable,
    EvidenceResumeMismatch,
    EvidenceStateError,
    EvidenceValidationReport,
    EvidenceWriter,
    FrozenArtifact,
    ObservedValue,
    PlannedRoot,
    RootObservation,
    ValidationStage,
    absent,
    captured_bytes,
    not_applicable,
    observed,
    unknown,
    validate_evidence_bundle,
)
from kit_llm.bench.golden import (
    GoldenCheck,
    GoldenCheckFailed,
    GoldenCorpusError,
    GoldenEntry,
    GoldenSuite,
    canonical_sha256,
    load_golden_suite,
    run_regression_checks,
)
from kit_llm.bench.harness import (
    AmbiguousRoot,
    AmbiguousScore,
    Bench,
    BenchArtifactError,
    BenchCase,
    BenchConfig,
    BenchIdentity,
    CellContext,
    FailureObservation,
    IncomparableRuns,
    LockUnavailable,
    RepeatResult,
    ResumeMismatch,
    RunLocked,
    RetryableCellError,
    diff_runs,
    ledger_cost,
)
from kit_llm.bench.replay import (
    ProviderExchange,
    ProviderFailureObservation,
    ProviderObservation,
    ReplayError,
    ReplayMismatch,
    ReplayProvider,
    ReplayStreamingUnsupported,
    ReplayTransport,
    ReplayUnconsumed,
    observe_provider,
)

__all__ = [
    "AmbiguousEvidenceAttempt",
    "AmbiguousRoot",
    "AmbiguousScore",
    "AttemptObservation",
    "Bench",
    "BenchArtifactError",
    "BenchCase",
    "BenchConfig",
    "BenchIdentity",
    "Cell",
    "CellContext",
    "CampaignProtocol",
    "EVIDENCE_BUNDLE_FORMAT",
    "EVIDENCE_BYTES_FORMAT",
    "EVIDENCE_FORMAT_VERSION",
    "EVIDENCE_RECORD_FORMAT",
    "EvidenceArtifactError",
    "EvidenceBundleLocked",
    "EvidenceIncomplete",
    "EvidenceIssue",
    "EvidenceLockUnavailable",
    "EvidenceResumeMismatch",
    "EvidenceStateError",
    "EvidenceValidationReport",
    "EvidenceWriter",
    "FailureObservation",
    "GoldenCheck",
    "GoldenCheckFailed",
    "GoldenCorpusError",
    "GoldenEntry",
    "GoldenSuite",
    "FrozenArtifact",
    "IncomparableRuns",
    "LockUnavailable",
    "ObservedValue",
    "PlannedRoot",
    "ProviderExchange",
    "ProviderFailureObservation",
    "ProviderObservation",
    "RepeatResult",
    "RootObservation",
    "ReplayError",
    "ReplayMismatch",
    "ReplayProvider",
    "ReplayStreamingUnsupported",
    "ReplayTransport",
    "ReplayUnconsumed",
    "ResumeMismatch",
    "RunLocked",
    "RetryableCellError",
    "ValidationStage",
    "absent",
    "captured_bytes",
    "canonical_sha256",
    "diff_runs",
    "expand",
    "ledger_cost",
    "load_golden_suite",
    "not_applicable",
    "observe_provider",
    "observed",
    "run_regression_checks",
    "unknown",
    "validate_evidence_bundle",
]
