import { describe, expect, it } from "vitest";
import {
  manifestRanges,
  parseLockfile,
  UnsupportedLockfileError,
} from "./index.js";

// Spec §9 test 1: fixtures for npm v2/v3, pnpm (v5/v6/v9 key shapes), yarn
// classic + berry → identical normalized output; scoped packages; unsupported
// formats produce the typed, user-facing error.

const NPM_V3 = JSON.stringify({
  name: "fixture",
  lockfileVersion: 3,
  packages: {
    "": {
      dependencies: { express: "^4.18.0" },
      devDependencies: { "@types/node": "^22.0.0" },
    },
    "node_modules/express": { version: "4.18.2" },
    "node_modules/@types/node": { version: "22.1.0" },
    "node_modules/express/node_modules/qs": { version: "6.11.0" },
    "node_modules/linked-pkg": { version: "1.0.0", link: true },
    "packages/workspace-a": { version: "0.0.1" },
  },
});

describe("parseNpmLockfile", () => {
  it("extracts direct + transitive deps with ranges from the root entry", () => {
    const deps = parseLockfile("package-lock.json", NPM_V3);
    const express = deps.find((d) => d.name === "express");
    expect(express).toMatchObject({ version: "4.18.2", direct: true, range: "^4.18.0" });

    const qs = deps.find((d) => d.name === "qs");
    expect(qs).toMatchObject({ version: "6.11.0", direct: false, range: null });
  });

  it("handles scoped packages and nested node_modules", () => {
    const deps = parseLockfile("package-lock.json", NPM_V3);
    const types = deps.find((d) => d.name === "@types/node");
    expect(types).toMatchObject({ version: "22.1.0", direct: true });
  });

  it("skips workspace links and non-node_modules paths", () => {
    const deps = parseLockfile("package-lock.json", NPM_V3);
    expect(deps.find((d) => d.name === "linked-pkg")).toBeUndefined();
    expect(deps.find((d) => d.name === "workspace-a")).toBeUndefined();
  });

  it("dedupes identical (name, version) pairs", () => {
    const lock = JSON.stringify({
      lockfileVersion: 3,
      packages: {
        "": {},
        "node_modules/a": { version: "1.0.0" },
        "node_modules/b/node_modules/a": { version: "1.0.0" },
      },
    });
    const deps = parseLockfile("package-lock.json", lock);
    expect(deps.filter((d) => d.name === "a")).toHaveLength(1);
  });

  it("rejects v1 lockfiles with a regenerate hint", () => {
    const v1 = JSON.stringify({ lockfileVersion: 1, dependencies: {} });
    expect(() => parseLockfile("package-lock.json", v1)).toThrow(UnsupportedLockfileError);
    expect(() => parseLockfile("package-lock.json", v1)).toThrow(/npm >= 7/);
  });

  it("rejects invalid JSON with a typed error", () => {
    expect(() => parseLockfile("package-lock.json", "not json{")).toThrow(
      UnsupportedLockfileError,
    );
  });
});

const PNPM_V9 = `
lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21
packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-x}
  '@babel/core@7.20.0(supports-color@9.0.0)':
    resolution: {integrity: sha512-y}
`;

const PNPM_V6 = `
lockfileVersion: '6.0'
importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21
packages:
  /lodash@4.17.21:
    resolution: {integrity: sha512-x}
  '/@scope/pkg@1.2.3':
    resolution: {integrity: sha512-y}
`;

const PNPM_V5 = `
lockfileVersion: 5.4
dependencies:
  lodash: 4.17.21
packages:
  /lodash/4.17.21:
    resolution: {integrity: sha512-x}
  /@scope/pkg/1.2.3_react@18.0.0:
    resolution: {integrity: sha512-y}
`;

describe("parsePnpmLockfile", () => {
  it("parses v9 keys incl. scoped + peer suffixes", () => {
    const deps = parseLockfile("pnpm-lock.yaml", PNPM_V9);
    expect(deps.find((d) => d.name === "lodash")).toMatchObject({
      version: "4.17.21",
      direct: true,
      range: "^4.17.21",
    });
    expect(deps.find((d) => d.name === "@babel/core")).toMatchObject({
      version: "7.20.0",
      direct: false,
    });
  });

  it("parses v6 keys (leading slash, @ separator)", () => {
    const deps = parseLockfile("pnpm-lock.yaml", PNPM_V6);
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "@scope/pkg")?.version).toBe("1.2.3");
  });

  it("parses v5 keys (slash separator, underscore peer suffix)", () => {
    const deps = parseLockfile("pnpm-lock.yaml", PNPM_V5);
    expect(deps.find((d) => d.name === "lodash")).toMatchObject({
      version: "4.17.21",
      direct: true,
    });
    expect(deps.find((d) => d.name === "@scope/pkg")?.version).toBe("1.2.3");
  });
});

const YARN_CLASSIC = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#hash"
  integrity sha512-x

"@scope/pkg@^1.0.0":
  version "1.0.1"
  resolved "https://registry.yarnpkg.com/@scope/pkg/-/pkg-1.0.1.tgz#hash"
  integrity sha512-y
`;

const YARN_BERRY = `# This file is generated by running "yarn install"

__metadata:
  version: 8
  cacheKey: 10

"lodash@npm:^4.17.21":
  version: 4.17.21
  resolution: "lodash@npm:4.17.21"

"@scope/pkg@npm:^1.0.0":
  version: 1.0.1
  resolution: "@scope/pkg@npm:1.0.1"

"my-workspace@workspace:.":
  version: 0.0.0-use.local
  resolution: "my-workspace@workspace:."
`;

describe("parseYarnLockfile", () => {
  const manifest = manifestRanges({ dependencies: { lodash: "^4.17.21" } });

  it("parses classic format; direct classification comes from the manifest", () => {
    const deps = parseLockfile("yarn.lock", YARN_CLASSIC, manifest);
    expect(deps.find((d) => d.name === "lodash")).toMatchObject({
      version: "4.17.21",
      direct: true,
      range: "^4.17.21",
    });
    expect(deps.find((d) => d.name === "@scope/pkg")).toMatchObject({
      version: "1.0.1",
      direct: false,
    });
  });

  it("parses berry format via resolution field, skipping workspace entries", () => {
    const deps = parseLockfile("yarn.lock", YARN_BERRY, manifest);
    expect(deps.find((d) => d.name === "lodash")?.version).toBe("4.17.21");
    expect(deps.find((d) => d.name === "@scope/pkg")?.version).toBe("1.0.1");
    expect(deps.find((d) => d.name === "my-workspace")).toBeUndefined();
  });
});

describe("parseLockfile dispatch", () => {
  it("rejects unknown filenames naming the supported formats", () => {
    expect(() => parseLockfile("bun.lockb", "")).toThrow(/package-lock\.json.*pnpm-lock\.yaml.*yarn\.lock/);
  });
});

describe("manifestRanges", () => {
  it("collects ranges across dep sections, first section wins", () => {
    const ranges = manifestRanges({
      dependencies: { a: "^1.0.0" },
      devDependencies: { a: "^2.0.0", b: "~3.0.0" },
    });
    expect(ranges.get("a")).toBe("^1.0.0");
    expect(ranges.get("b")).toBe("~3.0.0");
  });

  it("tolerates garbage input", () => {
    expect(manifestRanges(null).size).toBe(0);
    expect(manifestRanges("x").size).toBe(0);
  });
});
